//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceDetail
    {
        public string BSYMM { get; set; }
        public string BSNUM { get; set; }
        public string BSREN { get; set; }
        public Nullable<decimal> BSVAL { get; set; }
        public Nullable<int> BSCOUNT { get; set; }
        public Nullable<decimal> BSDAYRAT { get; set; }
        public Nullable<decimal> BSBAL { get; set; }
        public string ADDUSR { get; set; }
        public Nullable<System.DateTime> ADDDAT { get; set; }
        public string TRUSR { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
    }
}
