//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCodeScaleB
    {
        public string ScaleId { get; set; }
        public int ItemOrder { get; set; }
        public string preChar { get; set; }
        public string FieldName { get; set; }
        public string afterChar { get; set; }
        public string TotalSizeIncludePre_After { get; set; }
        public string NotEnoughWithChar { get; set; }
        public string AddBeforeOrAfter { get; set; }
        public string decimalCnt { get; set; }
        public string Remark { get; set; }
        public string CanChange { get; set; }
        public string IsDataOut { get; set; }
        public string IsShowThousandthsSign { get; set; }
        public string StartChar { get; set; }
    
        public virtual BarCodeScaleA BarCodeScaleA { get; set; }
    }
}
