//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarCodeScaleA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BarCodeScaleA()
        {
            this.BarCodeScaleBs = new HashSet<BarCodeScaleB>();
        }
    
        public string ScaleId { get; set; }
        public string ScaleName { get; set; }
        public string ScaleDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public string delimiter { get; set; }
        public string Source { get; set; }
        public string OrderBy1 { get; set; }
        public string OrderBy2 { get; set; }
        public string OrderBy3 { get; set; }
        public string OrderBy4 { get; set; }
        public string OrderBy5 { get; set; }
        public string MustGreaterThanZeroField { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BarCodeScaleB> BarCodeScaleBs { get; set; }
    }
}
