//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCU()
        {
            this.BBNKs = new HashSet<BBNK>();
            this.BCUGs = new HashSet<BCUG>();
            this.BCUSSALES = new HashSet<BCUSSALE>();
            this.BDEPs = new HashSet<BDEP>();
            this.BINTs = new HashSet<BINT>();
            this.BPSNs = new HashSet<BPSN>();
            this.BSTPs = new HashSet<BSTP>();
            this.BSTP_RSWA = new HashSet<BSTP_RSWA>();
            this.RIPAs = new HashSet<RIPA>();
            this.RIPAs1 = new HashSet<RIPA>();
            this.RIRAs = new HashSet<RIRA>();
            this.RISAs = new HashSet<RISA>();
            this.RSIAAs = new HashSet<RSIAA>();
            this.RSIAAs1 = new HashSet<RSIAA>();
            this.RSIFAs = new HashSet<RSIFA>();
            this.RSIHAs = new HashSet<RSIHA>();
            this.RSIIAs = new HashSet<RSIIA>();
            this.RSIMAs = new HashSet<RSIMA>();
            this.RSIMAs1 = new HashSet<RSIMA>();
            this.RSIQAs = new HashSet<RSIQA>();
            this.RSIRAs = new HashSet<RSIRA>();
            this.RSISAs = new HashSet<RSISA>();
            this.RSIYAs = new HashSet<RSIYA>();
            this.RSPPAs = new HashSet<RSPPA>();
            this.RSRAs = new HashSet<RSRA>();
            this.RSTPs = new HashSet<RSTP>();
            this.RSZABBs = new HashSet<RSZABB>();
            this.RSZBBBs = new HashSet<RSZBBB>();
            this.RTSAAs = new HashSet<RTSAA>();
            this.Users = new HashSet<User>();
            this.UserObjects = new HashSet<UserObject>();
        }
    
        public string BCTYP { get; set; }
        public string BCNUM { get; set; }
        public string BCCNX { get; set; }
        public string BCNAM { get; set; }
        public string BCNME { get; set; }
        public string BCCJ5 { get; set; }
        public string BCSHT { get; set; }
        public string BCOOU { get; set; }
        public string BCZON { get; set; }
        public string BCADR { get; set; }
        public string BCCTY { get; set; }
        public string BCTWN { get; set; }
        public string BCNAT { get; set; }
        public string BCZN4 { get; set; }
        public string BCAR4 { get; set; }
        public string BCCT4 { get; set; }
        public string BCTW4 { get; set; }
        public string BCNA4 { get; set; }
        public string BCEML { get; set; }
        public string BCMN1 { get; set; }
        public string BCMN2 { get; set; }
        public string BCMN3 { get; set; }
        public string BCMN4 { get; set; }
        public string BCFAX { get; set; }
        public string BCFA3 { get; set; }
        public string BCFA4 { get; set; }
        public string BCTEL { get; set; }
        public string BCTE3 { get; set; }
        public string BCTE4 { get; set; }
        public string BCSAL { get; set; }
        public string BCITM { get; set; }
        public string BCBCS { get; set; }
        public Nullable<double> BCDCX { get; set; }
        public string BCCS1 { get; set; }
        public string BCINT { get; set; }
        public string BCINV { get; set; }
        public string BCZN2 { get; set; }
        public string BCINA { get; set; }
        public string BCCT2 { get; set; }
        public string BCTW2 { get; set; }
        public string BCNA2 { get; set; }
        public Nullable<System.DateTime> BCDAT { get; set; }
        public Nullable<System.DateTime> BCDA2 { get; set; }
        public string BCPAY { get; set; }
        public Nullable<int> BCDAY { get; set; }
        public string BCRMK { get; set; }
        public string BCNOT { get; set; }
        public string BCMCT { get; set; }
        public string BCPOS { get; set; }
        public Nullable<System.DateTime> BCBIR { get; set; }
        public string BCBNK { get; set; }
        public string BCBK2 { get; set; }
        public string BCACT { get; set; }
        public string BCAT2 { get; set; }
        public string BCCLS { get; set; }
        public string BCONU { get; set; }
        public string BCTE2 { get; set; }
        public string BCPDT { get; set; }
        public string BCMEN { get; set; }
        public string BCACN { get; set; }
        public string BCEDT { get; set; }
        public string BCCLA { get; set; }
        public double BCAMT { get; set; }
        public string BCATN { get; set; }
        public string BCNNU { get; set; }
        public string BCFLR { get; set; }
        public Nullable<double> BCLAN { get; set; }
        public string BCBUY { get; set; }
        public string BCSFG { get; set; }
        public string BCDOC { get; set; }
        public string BCODO { get; set; }
        public Nullable<double> BCRAT { get; set; }
        public Nullable<double> BCCRD { get; set; }
        public string BCREG { get; set; }
        public string BCRE3 { get; set; }
        public string BCRE4 { get; set; }
        public string BCRE5 { get; set; }
        public string BCRE6 { get; set; }
        public string BCRE7 { get; set; }
        public string BCVYM { get; set; }
        public Nullable<double> BCPDY { get; set; }
        public string BCTXK { get; set; }
        public string BCADP { get; set; }
        public string BCORD { get; set; }
        public decimal BCCMS { get; set; }
        public decimal BCHMS { get; set; }
        public string RADPT { get; set; }
        public Nullable<System.DateTime> BCCID { get; set; }
        public string BCINP { get; set; }
        public Nullable<System.DateTime> BCIND { get; set; }
        public Nullable<System.DateTime> BCDA3 { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string BCCMN { get; set; }
        public string IsOutStore { get; set; }
        public Nullable<decimal> DrawnRatio { get; set; }
        public Nullable<decimal> CreditcardRatio { get; set; }
        public string B2BCNS { get; set; }
        public string IsAllocationStore { get; set; }
        public string RSICPrePickRBDPC { get; set; }
        public string LoginList { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BBNK> BBNKs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCUG> BCUGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCUSSALE> BCUSSALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BDEP> BDEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINT> BINTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPSN> BPSNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSTP> BSTPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSTP_RSWA> BSTP_RSWA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIPA> RIPAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIPA> RIPAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIRA> RIRAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISA> RISAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIAA> RSIAAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIAA> RSIAAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIFA> RSIFAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIHA> RSIHAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIIA> RSIIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIMA> RSIMAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIMA> RSIMAs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIQA> RSIQAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIRA> RSIRAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSISA> RSISAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIYA> RSIYAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSPPA> RSPPAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRA> RSRAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSTP> RSTPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSZABB> RSZABBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSZBBB> RSZBBBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RTSAA> RTSAAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserObject> UserObjects { get; set; }
    }
}
