//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCUG
    {
        public string BCNUM { get; set; }
        public string BCFLR { get; set; }
        public string BCNNU { get; set; }
        public string BCNAM { get; set; }
        public string BCTEL { get; set; }
        public string BCFAX { get; set; }
        public Nullable<double> BCLAN { get; set; }
    
        public virtual BCU BCU { get; set; }
    }
}
