//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCVP
    {
        public string BCNUM { get; set; }
        public string BCONU { get; set; }
        public string BCNAM { get; set; }
        public string BCCJ5 { get; set; }
        public string BCSEX { get; set; }
        public string BCMAR { get; set; }
        public Nullable<System.DateTime> BCBIR { get; set; }
        public string BCCLA { get; set; }
        public string BCCLS { get; set; }
        public string BCJOB { get; set; }
        public string BCPOS { get; set; }
        public string BCINC { get; set; }
        public string BCMVN { get; set; }
        public string BCBUY { get; set; }
        public string BCPLN { get; set; }
        public string BCMGC { get; set; }
        public string BCMGN { get; set; }
        public string BCTVC { get; set; }
        public Nullable<System.DateTime> BCBR2 { get; set; }
        public string BCNM2 { get; set; }
        public Nullable<System.DateTime> BCBR3 { get; set; }
        public Nullable<System.DateTime> BCDA1 { get; set; }
        public Nullable<System.DateTime> BCDA5 { get; set; }
        public Nullable<System.DateTime> BCDA2 { get; set; }
        public string BCCNO { get; set; }
        public string BCZIP { get; set; }
        public string BCCOD { get; set; }
        public string BCCD2 { get; set; }
        public string BCTL1 { get; set; }
        public string BCCT1 { get; set; }
        public string BCTW1 { get; set; }
        public string BCAD1 { get; set; }
        public string BCTL2 { get; set; }
        public string BCCT2 { get; set; }
        public string BCTW2 { get; set; }
        public string BCAD2 { get; set; }
        public string BCFAX { get; set; }
        public Nullable<System.DateTime> BCDA4 { get; set; }
        public string BCCNU { get; set; }
        public string BCFOR { get; set; }
        public string BCMAL { get; set; }
        public string BCGSM { get; set; }
        public string BCINV { get; set; }
        public string BCINT { get; set; }
        public string BCBBC { get; set; }
        public Nullable<double> BCDCX { get; set; }
        public string BCMNE { get; set; }
        public Nullable<System.DateTime> BCDA3 { get; set; }
        public Nullable<double> BCTMT { get; set; }
        public string BCRMK { get; set; }
        public Nullable<System.DateTime> BCRMT { get; set; }
        public Nullable<double> BCDOT { get; set; }
        public Nullable<double> BCDO1 { get; set; }
        public Nullable<System.DateTime> BCDA6 { get; set; }
        public string BCSHT { get; set; }
        public string BCBOS { get; set; }
        public string BCWWW { get; set; }
        public string BCAD3 { get; set; }
        public string BCAD4 { get; set; }
        public string BCMNY { get; set; }
        public string BCPWD { get; set; }
        public string BCZON { get; set; }
        public string BCTNM { get; set; }
        public string BCTCL { get; set; }
        public string BCTDN { get; set; }
        public string BCTNN { get; set; }
        public string BCTPY { get; set; }
        public string BCRTN { get; set; }
        public Nullable<int> BCLOS { get; set; }
        public Nullable<int> BCDOM { get; set; }
        public Nullable<System.DateTime> BCDA8 { get; set; }
        public Nullable<System.DateTime> BCDA9 { get; set; }
        public Nullable<decimal> BCADV { get; set; }
        public string BCRM2 { get; set; }
        public Nullable<decimal> TotalConsumptionMoney { get; set; }
        public Nullable<System.DateTime> TotalConsumptionsDate { get; set; }
        public Nullable<System.DateTime> TotalConsumptioneDate { get; set; }
        public Nullable<decimal> ConsumptionsFristDateMoney { get; set; }
    }
}
