//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCVR
    {
        public string BCNUM { get; set; }
        public string BCITM { get; set; }
        public string BCNAM { get; set; }
        public string BCCJ5 { get; set; }
        public string BCRIN { get; set; }
        public string BCSEX { get; set; }
        public Nullable<System.DateTime> BCBIR { get; set; }
        public string BCCNO { get; set; }
        public string BCZIP { get; set; }
        public string BCCOD { get; set; }
        public string BCTL1 { get; set; }
        public string BCAD1 { get; set; }
        public string BCTL2 { get; set; }
        public string BCCD2 { get; set; }
        public string BCAD2 { get; set; }
        public string BCFAX { get; set; }
        public string BCMAL { get; set; }
        public string BCGSM { get; set; }
        public string BCINV { get; set; }
        public string BCINT { get; set; }
        public string BCBBC { get; set; }
        public string BCRMK { get; set; }
    }
}
