//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDEP
    {
        public string BDNUM { get; set; }
        public string BDITM { get; set; }
        public string BDDEP { get; set; }
        public string BDTIT { get; set; }
        public string BDMN2 { get; set; }
        public string BDTEL { get; set; }
        public string BDGSM { get; set; }
        public string BDFAX { get; set; }
        public string BDEML { get; set; }
        public string BDRMK { get; set; }
        public string BDRE1 { get; set; }
        public string BDRE2 { get; set; }
    
        public virtual BCU BCU { get; set; }
    }
}
