//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINT
    {
        public string BINUM { get; set; }
        public string BIITM { get; set; }
        public string BICS1 { get; set; }
        public string BIINT { get; set; }
        public string BIINV { get; set; }
        public string BIZN2 { get; set; }
        public string BIINA { get; set; }
        public string BICTY { get; set; }
        public string BITWN { get; set; }
        public string BINAT { get; set; }
    
        public virtual BCU BCU { get; set; }
    }
}
