//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONUSFL1
    {
        public System.DateTime BSDAY { get; set; }
        public string BSREN { get; set; }
        public string BSITM { get; set; }
        public string BSNCR { get; set; }
        public string BSCLR { get; set; }
        public string BSCNS { get; set; }
        public string BSNUM { get; set; }
        public string BPTIT { get; set; }
        public string BSCN2 { get; set; }
        public decimal BSUP1 { get; set; }
        public decimal BSUPD { get; set; }
        public decimal BSDCX { get; set; }
        public int BSCOU { get; set; }
        public decimal BSAMT { get; set; }
    }
}
