//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONUSFL2
    {
        public string BSYEA { get; set; }
        public string BSMON { get; set; }
        public string BSNUM { get; set; }
        public string BPTIT { get; set; }
        public string BSCNS { get; set; }
        public Nullable<int> BSCOU { get; set; }
        public Nullable<int> DRATE { get; set; }
        public Nullable<decimal> RXTGT { get; set; }
        public Nullable<decimal> RXAMT { get; set; }
        public Nullable<int> MRATE { get; set; }
        public Nullable<decimal> RXAM1 { get; set; }
        public Nullable<decimal> BSAMT { get; set; }
    }
}
