//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONUSSETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BONUSSETA()
        {
            this.BONUSSETBRATs = new HashSet<BONUSSETBRAT>();
            this.BONUSSETBWTs = new HashSet<BONUSSETBWT>();
        }
    
        public string BOREN { get; set; }
        public string BOBCS { get; set; }
        public string BOITM { get; set; }
        public string BOCNS { get; set; }
        public string BOTIT { get; set; }
        public string BODA1 { get; set; }
        public string BODA2 { get; set; }
        public string BOTYP { get; set; }
        public string BONAM { get; set; }
        public string BOCLS { get; set; }
        public string BOITE { get; set; }
        public string BORATYP { get; set; }
        public Nullable<decimal> BORAVAL { get; set; }
        public string BORAMOD { get; set; }
        public string BOWTTYP { get; set; }
        public Nullable<decimal> BOWTVAL { get; set; }
        public string BOWTMOD { get; set; }
        public string BOAVG { get; set; }
        public Nullable<System.DateTime> BODA4 { get; set; }
        public string TRUSR { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONUSSETBRAT> BONUSSETBRATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONUSSETBWT> BONUSSETBWTs { get; set; }
    }
}
