//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONUSSETBRAT
    {
        public string BBREN { get; set; }
        public string BBITM { get; set; }
        public Nullable<decimal> BBST1 { get; set; }
        public Nullable<decimal> BBST2 { get; set; }
        public Nullable<decimal> BBVAL { get; set; }
    
        public virtual BONUSSETA BONUSSETA { get; set; }
    }
}
