//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BONU
    {
        public System.DateTime BSDAY { get; set; }
        public string BSREN { get; set; }
        public string BSITM { get; set; }
        public string BSONU { get; set; }
        public Nullable<decimal> BSDCX { get; set; }
        public Nullable<decimal> BSAM1 { get; set; }
        public Nullable<decimal> BSRTO { get; set; }
        public string BSCTS { get; set; }
        public Nullable<System.DateTime> BCDAY { get; set; }
        public string BSCNS { get; set; }
        public string BSNUM { get; set; }
        public Nullable<decimal> BSDC1 { get; set; }
        public Nullable<decimal> BSAMT { get; set; }
        public string BSRMK { get; set; }
    }
}
