//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPSN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPSN()
        {
            this.BCUSSALES = new HashSet<BCUSSALE>();
            this.BSTIs = new HashSet<BSTI>();
        }
    
        public string BPENO { get; set; }
        public string BPNME { get; set; }
        public string BPENM { get; set; }
        public string BPCJ5 { get; set; }
        public string BPIDN { get; set; }
        public Nullable<System.DateTime> BPBTH { get; set; }
        public string BPSEX { get; set; }
        public string BPBLD { get; set; }
        public string BPDPT { get; set; }
        public string BPTIT { get; set; }
        public string BPADD { get; set; }
        public string BPTEL { get; set; }
        public string BPMOR { get; set; }
        public string BPBBC { get; set; }
        public string BPEML { get; set; }
        public string BPCMN { get; set; }
        public string BPCTL { get; set; }
        public string BPCMR { get; set; }
        public string BPCBC { get; set; }
        public string BPCEL { get; set; }
        public string BPROT { get; set; }
        public string BPSCH { get; set; }
        public string BPPAD { get; set; }
        public string BPTL2 { get; set; }
        public string BPLVL { get; set; }
        public Nullable<System.DateTime> BPFDY { get; set; }
        public Nullable<System.DateTime> BPEDY { get; set; }
        public string BPRMK { get; set; }
        public string BPAWD { get; set; }
        public string BPNOT { get; set; }
        public string BPCNU { get; set; }
        public string BPMAR { get; set; }
        public string BPREA { get; set; }
        public string BPJOB { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
    
        public virtual BCU BCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCUSSALE> BCUSSALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSTI> BSTIs { get; set; }
        public virtual UserObject UserObject { get; set; }
    }
}
