//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRPC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRPC()
        {
            this.RSRHAs = new HashSet<RSRHA>();
        }
    
        public string BANUM { get; set; }
        public string BANAM { get; set; }
        public string BALIT { get; set; }
        public Nullable<System.DateTime> BADAT { get; set; }
        public string BAUSR { get; set; }
        public string BAUDP { get; set; }
        public string TRMOD { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRHA> RSRHAs { get; set; }
    }
}
