//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSDA
    {
        public string BANUM { get; set; }
        public string BANAM { get; set; }
        public string BACJ5 { get; set; }
        public string BACTS { get; set; }
        public string BAFNU { get; set; }
        public Nullable<System.DateTime> BADAY { get; set; }
        public System.DateTime BASDT { get; set; }
        public Nullable<System.DateTime> BAEDT { get; set; }
        public string BATYP { get; set; }
        public string BACTN { get; set; }
        public Nullable<System.DateTime> BAIDT { get; set; }
        public Nullable<System.DateTime> BAODT { get; set; }
        public string BATX0 { get; set; }
        public string BABCS { get; set; }
        public string BAMN1 { get; set; }
        public string BAME1 { get; set; }
        public string BAME2 { get; set; }
        public string BAREN { get; set; }
        public Nullable<double> BABAS { get; set; }
        public string SPNAM { get; set; }
        public string SPSET { get; set; }
        public string BSRMK { get; set; }
    }
}
