//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSDAT
    {
        public System.DateTime BSDAT1 { get; set; }
        public Nullable<short> BSYEA { get; set; }
        public Nullable<short> BSMON { get; set; }
        public Nullable<short> BSDAY { get; set; }
        public Nullable<short> BSWEK { get; set; }
        public Nullable<short> BSQTR { get; set; }
        public Nullable<short> BSSES { get; set; }
        public Nullable<short> BSWCT { get; set; }
        public Nullable<short> BSWCN { get; set; }
        public string BSSPE { get; set; }
        public string BSRMK { get; set; }
        public Nullable<short> BSDCT { get; set; }
        public Nullable<short> BSFST { get; set; }
    }
}
