//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSDM
    {
        public string BSNUM { get; set; }
        public string BSCTS { get; set; }
        public System.DateTime BSSDT { get; set; }
        public string BSITM { get; set; }
        public string BSSYM { get; set; }
        public string BSEYM { get; set; }
        public Nullable<decimal> BSVAL { get; set; }
    }
}
