//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSGR
    {
        public string BSNUM { get; set; }
        public Nullable<System.DateTime> BSDT1 { get; set; }
        public string BSMEN { get; set; }
        public string BSCNS { get; set; }
        public string BSCUS { get; set; }
        public Nullable<System.DateTime> BSDT2 { get; set; }
        public Nullable<System.DateTime> BSDT3 { get; set; }
        public string BSONU { get; set; }
        public Nullable<double> BSQTY { get; set; }
        public string BSNAM { get; set; }
        public Nullable<double> BSDEP { get; set; }
        public string BSRMK { get; set; }
        public Nullable<System.DateTime> BSDT4 { get; set; }
        public string BSREN { get; set; }
        public string BSMAL { get; set; }
        public Nullable<double> BSUPC { get; set; }
        public Nullable<System.DateTime> BSDT5 { get; set; }
        public Nullable<System.DateTime> BSDT6 { get; set; }
        public string BSMN2 { get; set; }
        public Nullable<System.DateTime> BSDT7 { get; set; }
        public string BSMN3 { get; set; }
        public string BSRER { get; set; }
        public string BSRMA { get; set; }
        public Nullable<double> BSDEB { get; set; }
        public Nullable<double> BSDCX { get; set; }
        public string BSCLS { get; set; }
        public string BSPAY { get; set; }
        public string BSCRD { get; set; }
        public string BSCRN { get; set; }
        public Nullable<double> BSAMT { get; set; }
        public string TRUSR { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
    }
}
