//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSHB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BSHB()
        {
            this.RSPBs = new HashSet<RSPB>();
        }
    
        public string BSNUM { get; set; }
        public string BSSEQ { get; set; }
        public string BSNCR { get; set; }
        public string BSONR { get; set; }
        public string BSNAM { get; set; }
        public string BSENM { get; set; }
        public string BSLAB { get; set; }
        public string BSCLR { get; set; }
        public string BSOCR { get; set; }
        public string BSMAT { get; set; }
        public string BSCLA { get; set; }
        public string BSCLS { get; set; }
        public string BSGLA { get; set; }
        public string BSGLB { get; set; }
        public string BSYEA { get; set; }
        public string BSSEA { get; set; }
        public string BSOYA { get; set; }
        public string BSOSA { get; set; }
        public string BSSEX { get; set; }
        public string BSUNI { get; set; }
        public string BSCUS { get; set; }
        public Nullable<double> BSDEP { get; set; }
        public Nullable<double> BSDEB { get; set; }
        public Nullable<double> BSDEC { get; set; }
        public Nullable<double> BSDED { get; set; }
        public double BSEEP { get; set; }
        public double BSEEB { get; set; }
        public Nullable<double> BSEEC { get; set; }
        public Nullable<double> BSEED { get; set; }
        public double BSQTL { get; set; }
        public Nullable<System.DateTime> BSDAT { get; set; }
        public Nullable<System.DateTime> BSDT4 { get; set; }
        public string BSUSR { get; set; }
        public string BSFAC { get; set; }
        public string BSMNY { get; set; }
        public Nullable<double> BSFOR { get; set; }
        public string BSMA1 { get; set; }
        public string BSMA2 { get; set; }
        public string BSGL1 { get; set; }
        public string BSGL2 { get; set; }
        public string BSGL3 { get; set; }
        public string BSGL4 { get; set; }
        public string BSRMK { get; set; }
        public string BSNNU { get; set; }
        public string BSDT7 { get; set; }
    
        public virtual BSHA BSHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSPB> RSPBs { get; set; }
    }
}
