//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSQTY
    {
        public string BSNUM { get; set; }
        public string BSNCR { get; set; }
        public string BSCLR { get; set; }
        public Nullable<double> BSQTY01 { get; set; }
        public Nullable<double> BSQTY02 { get; set; }
        public Nullable<double> BSQTY03 { get; set; }
        public Nullable<double> BSQTY04 { get; set; }
        public Nullable<double> BSQTY05 { get; set; }
        public Nullable<double> BSQTY06 { get; set; }
        public Nullable<double> BSQTY07 { get; set; }
        public Nullable<double> BSQTY08 { get; set; }
        public Nullable<double> BSQTY09 { get; set; }
        public Nullable<double> BSQTY10 { get; set; }
        public Nullable<double> BSQTY11 { get; set; }
        public Nullable<double> BSQTY12 { get; set; }
        public Nullable<double> BSQTY13 { get; set; }
        public Nullable<double> BSQTY14 { get; set; }
        public Nullable<double> BSQTY15 { get; set; }
        public Nullable<double> BSQTY16 { get; set; }
        public Nullable<double> BSQTY17 { get; set; }
        public Nullable<double> BSQTY18 { get; set; }
        public Nullable<double> BSQTY19 { get; set; }
        public Nullable<double> BSQTY20 { get; set; }
        public Nullable<double> BSQTY21 { get; set; }
        public Nullable<double> BSQTY22 { get; set; }
        public Nullable<double> BSQTY23 { get; set; }
        public Nullable<double> BSQTY24 { get; set; }
        public Nullable<double> BSQTY25 { get; set; }
        public Nullable<double> BSQTY26 { get; set; }
        public Nullable<double> BSQTY27 { get; set; }
        public Nullable<double> BSQTY28 { get; set; }
        public Nullable<double> BSQTY29 { get; set; }
        public Nullable<double> BSQTY30 { get; set; }
    }
}
