//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSSB
    {
        public string BBREN { get; set; }
        public decimal BBITM { get; set; }
        public string BBTYP { get; set; }
        public Nullable<decimal> BBDIM { get; set; }
        public string BBGRE { get; set; }
        public string BBDC0 { get; set; }
        public Nullable<double> BBDCS { get; set; }
        public Nullable<double> BBDCE { get; set; }
        public Nullable<double> BBDCX { get; set; }
        public string BBREV { get; set; }
        public Nullable<double> BBGOL { get; set; }
        public Nullable<double> BBTOP { get; set; }
        public Nullable<double> BBIDC { get; set; }
    
        public virtual BSSA BSSA { get; set; }
    }
}
