//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSTI
    {
        public string BSNUM { get; set; }
        public string BSNAM { get; set; }
        public string BSGLA { get; set; }
        public string BSGLC { get; set; }
        public string BSUNI { get; set; }
        public string BSSTO { get; set; }
        public Nullable<System.DateTime> BSDAT { get; set; }
        public string BSUSR { get; set; }
        public string TRMOD { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string BSCLA { get; set; }
    
        public virtual BPSN BPSN { get; set; }
    }
}
