//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSTL_20131120BK
    {
        public string BSNCR { get; set; }
        public string BSCLR { get; set; }
        public string BSOCR { get; set; }
        public string BSONR { get; set; }
        public string BSMAT { get; set; }
        public Nullable<decimal> BSUPC { get; set; }
        public Nullable<decimal> BSAVG { get; set; }
        public Nullable<double> BSSVG { get; set; }
        public Nullable<decimal> BSDEP { get; set; }
        public Nullable<decimal> BSDEB { get; set; }
        public Nullable<decimal> BSDEC { get; set; }
        public Nullable<decimal> BSDED { get; set; }
        public Nullable<decimal> BSEEP { get; set; }
        public Nullable<decimal> BSEEB { get; set; }
        public Nullable<decimal> BSEEC { get; set; }
        public Nullable<decimal> BSEED { get; set; }
        public string BSPIC { get; set; }
        public Nullable<System.DateTime> BSDT4 { get; set; }
        public Nullable<System.DateTime> BSDT5 { get; set; }
        public Nullable<double> BSFOR { get; set; }
        public string BSMNY { get; set; }
        public Nullable<double> BSTIM { get; set; }
        public Nullable<double> BSLEV { get; set; }
        public Nullable<double> BSHEV { get; set; }
        public Nullable<double> BSQTI { get; set; }
        public string BSMA1 { get; set; }
        public string BSMA2 { get; set; }
        public string BSYEA { get; set; }
        public string BSSEA { get; set; }
        public string BSOYA { get; set; }
        public string BSOSA { get; set; }
        public string BSDT6 { get; set; }
        public string BSDT7 { get; set; }
        public string BSPS3 { get; set; }
        public string BSPS4 { get; set; }
        public Nullable<System.DateTime> BSDT8 { get; set; }
        public Nullable<double> BSPER { get; set; }
        public string BSOBC { get; set; }
        public string BSIBC { get; set; }
        public Nullable<double> BSMOC { get; set; }
        public Nullable<double> BSGAC { get; set; }
        public string BSSHL { get; set; }
        public string BSMA3 { get; set; }
        public string BSMA4 { get; set; }
    }
}
