//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSTP
    {
        public string BSNUM { get; set; }
        public string BSCNS { get; set; }
        public string BSNCR { get; set; }
        public string BSCLR { get; set; }
        public string BSITZ { get; set; }
        public string BSSIZ { get; set; }
        public string BSPOS { get; set; }
        public string BSPS2 { get; set; }
        public Nullable<double> BSQTY { get; set; }
        public Nullable<double> BSQTO { get; set; }
        public Nullable<double> BSQTI { get; set; }
        public Nullable<System.DateTime> BSDT1 { get; set; }
        public Nullable<System.DateTime> BSDT2 { get; set; }
        public Nullable<System.DateTime> BSDT3 { get; set; }
        public Nullable<System.DateTime> BSDT4 { get; set; }
        public Nullable<System.DateTime> BSDT5 { get; set; }
        public string BSRMK { get; set; }
        public Nullable<int> BSQTD { get; set; }
        public Nullable<int> BSLEV { get; set; }
        public Nullable<int> BSHEV { get; set; }
        public string IFEXPLEV { get; set; }
    
        public virtual BCU BCU { get; set; }
        public virtual BSTO BSTO { get; set; }
    }
}
