//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSTXA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BSTXA()
        {
            this.BSTNs = new HashSet<BSTN>();
        }
    
        public string BSCLS { get; set; }
        public string BSSIZ01 { get; set; }
        public string BSSIZ02 { get; set; }
        public string BSSIZ03 { get; set; }
        public string BSSIZ04 { get; set; }
        public string BSSIZ05 { get; set; }
        public string BSSIZ06 { get; set; }
        public string BSSIZ07 { get; set; }
        public string BSSIZ08 { get; set; }
        public string BSSIZ09 { get; set; }
        public string BSSIZ10 { get; set; }
        public string BSSIZ11 { get; set; }
        public string BSSIZ12 { get; set; }
        public string BSSIZ13 { get; set; }
        public string BSSIZ14 { get; set; }
        public string BSSIZ15 { get; set; }
        public string BSSIZ16 { get; set; }
        public string BSSIZ17 { get; set; }
        public string BSSIZ18 { get; set; }
        public string BSSIZ19 { get; set; }
        public string BSSIZ20 { get; set; }
        public Nullable<decimal> BSTSIZ { get; set; }
        public string BSSIZ21 { get; set; }
        public string BSSIZ22 { get; set; }
        public string BSSIZ23 { get; set; }
        public string BSSIZ24 { get; set; }
        public string BSSIZ25 { get; set; }
        public string BSSIZ26 { get; set; }
        public string BSSIZ27 { get; set; }
        public string BSSIZ28 { get; set; }
        public string BSSIZ29 { get; set; }
        public string BSSIZ30 { get; set; }
        public string BSLOC01 { get; set; }
        public string BSLOC02 { get; set; }
        public string BSLOC03 { get; set; }
        public string BSLOC04 { get; set; }
        public string BSLOC05 { get; set; }
        public string BSLOC06 { get; set; }
        public string BSLOC07 { get; set; }
        public string BSLOC08 { get; set; }
        public string BSLOC09 { get; set; }
        public string BSLOC10 { get; set; }
        public string BSLOC11 { get; set; }
        public string BSLOC12 { get; set; }
        public string BSLOC13 { get; set; }
        public string BSLOC14 { get; set; }
        public string BSLOC15 { get; set; }
        public string BSLOC16 { get; set; }
        public string BSLOC17 { get; set; }
        public string BSLOC18 { get; set; }
        public string BSLOC19 { get; set; }
        public string BSLOC20 { get; set; }
        public string BSLOC21 { get; set; }
        public string BSLOC22 { get; set; }
        public string BSLOC23 { get; set; }
        public string BSLOC24 { get; set; }
        public string BSLOC25 { get; set; }
        public string BSLOC26 { get; set; }
        public string BSLOC27 { get; set; }
        public string BSLOC28 { get; set; }
        public string BSLOC29 { get; set; }
        public string BSLOC30 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BSTN> BSTNs { get; set; }
    }
}
