//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSTXB
    {
        public string BSCLS { get; set; }
        public string CultureInfo { get; set; }
        public string BSSIZ01 { get; set; }
        public string BSSIZ02 { get; set; }
        public string BSSIZ03 { get; set; }
        public string BSSIZ04 { get; set; }
        public string BSSIZ05 { get; set; }
        public string BSSIZ06 { get; set; }
        public string BSSIZ07 { get; set; }
        public string BSSIZ08 { get; set; }
        public string BSSIZ09 { get; set; }
        public string BSSIZ10 { get; set; }
        public string BSSIZ11 { get; set; }
        public string BSSIZ12 { get; set; }
        public string BSSIZ13 { get; set; }
        public string BSSIZ14 { get; set; }
        public string BSSIZ15 { get; set; }
        public string BSSIZ16 { get; set; }
        public string BSSIZ17 { get; set; }
        public string BSSIZ18 { get; set; }
        public string BSSIZ19 { get; set; }
        public string BSSIZ20 { get; set; }
        public string BSSIZ21 { get; set; }
        public string BSSIZ22 { get; set; }
        public string BSSIZ23 { get; set; }
        public string BSSIZ24 { get; set; }
        public string BSSIZ25 { get; set; }
        public string BSSIZ26 { get; set; }
        public string BSSIZ27 { get; set; }
        public string BSSIZ28 { get; set; }
        public string BSSIZ29 { get; set; }
        public string BSSIZ30 { get; set; }
    }
}
