//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTRX
    {
        public int BCREN { get; set; }
        public string BCFIN { get; set; }
        public System.DateTime BCDAT { get; set; }
        public string BCKEY { get; set; }
        public string BCNUM { get; set; }
        public string MachineNo { get; set; }
        public string BCCLS { get; set; }
    }
}
