//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLMoneyA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLMoneyA()
        {
            this.CLMoneyBs = new HashSet<CLMoneyB>();
        }
    
        public string RAREN { get; set; }
        public System.DateTime RADAY { get; set; }
        public string RACNS { get; set; }
        public string RANUM { get; set; }
        public string RAINN { get; set; }
        public string RAINV { get; set; }
        public Nullable<int> RAINQ { get; set; }
        public string RACS1 { get; set; }
        public string RACS2 { get; set; }
        public decimal RATOL { get; set; }
        public decimal RATAX { get; set; }
        public decimal RAAMT { get; set; }
        public string RAINC { get; set; }
        public string RASRC { get; set; }
        public string RARMA { get; set; }
        public string ADDMen { get; set; }
        public System.DateTime ADDDate { get; set; }
        public string TRUSR { get; set; }
        public System.DateTime TRDAT { get; set; }
        public string RAOEN { get; set; }
        public Nullable<decimal> RAPaid { get; set; }
        public string RASAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLMoneyB> CLMoneyBs { get; set; }
    }
}
