//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOrderD
    {
        public string RDREN { get; set; }
        public string RDITM { get; set; }
        public Nullable<int> RDSerial { get; set; }
        public string RDNCR { get; set; }
        public string RDNAM { get; set; }
        public Nullable<System.DateTime> RDDAY { get; set; }
        public string RDRER { get; set; }
        public string RDINV { get; set; }
        public Nullable<decimal> RDAMT { get; set; }
        public string RDShare { get; set; }
        public string RDPick { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
    
        public virtual CLOrderA CLOrderA { get; set; }
    }
}
