//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOrderA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLOrderA()
        {
            this.CLOrderBs = new HashSet<CLOrderB>();
            this.CLOrderCs = new HashSet<CLOrderC>();
            this.CLOrderDs = new HashSet<CLOrderD>();
        }
    
        public string RAREN { get; set; }
        public System.DateTime RADAY { get; set; }
        public string RACNS { get; set; }
        public string RANUM { get; set; }
        public string RACLA { get; set; }
        public int RAQTY { get; set; }
        public decimal RATOL { get; set; }
        public decimal RAPaid { get; set; }
        public decimal RAUnpaid { get; set; }
        public string RARMA { get; set; }
        public string RATHR { get; set; }
        public string RAAUD { get; set; }
        public string RASAL { get; set; }
        public string ADDMen { get; set; }
        public System.DateTime ADDDate { get; set; }
        public string TRUSR { get; set; }
        public System.DateTime TRDAT { get; set; }
        public string UseBirthdayDiscount { get; set; }
        public Nullable<decimal> AllOffset { get; set; }
        public Nullable<decimal> BonusOffset { get; set; }
        public Nullable<decimal> ShoppingGoldOffset { get; set; }
        public string RASRC { get; set; }
        public Nullable<int> RAPOT { get; set; }
        public string RAOpen { get; set; }
        public string RAOEN { get; set; }
        public string RARER { get; set; }
        public string RAECN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLOrderB> CLOrderBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLOrderC> CLOrderCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLOrderD> CLOrderDs { get; set; }
    }
}
