//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLOrderB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBGET { get; set; }
        public string RBONU { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBSIZ { get; set; }
        public int RBQTY { get; set; }
        public decimal RBDPC { get; set; }
        public decimal RBDCX { get; set; }
        public decimal RBUP1 { get; set; }
        public decimal RBUPC { get; set; }
        public decimal RBAM1 { get; set; }
        public decimal RBAMT { get; set; }
        public Nullable<decimal> RBFRE { get; set; }
        public Nullable<decimal> RBPaid { get; set; }
        public Nullable<decimal> RBUnpaid { get; set; }
        public string RBSTA { get; set; }
        public string RBCNS { get; set; }
        public string RBRER { get; set; }
        public string RBARE { get; set; }
        public string ReverseMen { get; set; }
        public Nullable<System.DateTime> ReverseDay { get; set; }
        public string ReverseTRUSR { get; set; }
        public Nullable<System.DateTime> ReverseTRDAT { get; set; }
        public string RBARV { get; set; }
        public string RBCTM { get; set; }
        public Nullable<decimal> OffsetMoney { get; set; }
    
        public virtual CLOrderA CLOrderA { get; set; }
    }
}
