//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeD
    {
        public string CodeType { get; set; }
        public string CodeId { get; set; }
        public int CodeHierarchy { get; set; }
        public string CodeParent { get; set; }
        public string CodeName { get; set; }
        public string CultureInfo { get; set; }
    
        public virtual CodeC CodeC { get; set; }
    }
}
