//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyWork_history
    {
        public string BSCNS { get; set; }
        public string BSYMM { get; set; }
        public Nullable<decimal> DayPerformance { get; set; }
        public Nullable<decimal> CashPerformance { get; set; }
        public Nullable<decimal> ReimbursementPerformance { get; set; }
        public Nullable<decimal> ReturnGoods { get; set; }
        public Nullable<decimal> Coupon { get; set; }
    }
}
