//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyWorkB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyWorkB()
        {
            this.DailyWorkCs = new HashSet<DailyWorkC>();
            this.DailyWorkDs = new HashSet<DailyWorkD>();
        }
    
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCOS { get; set; }
        public string PerformanceComputing { get; set; }
        public string IsOut { get; set; }
        public string GoodSituation { get; set; }
        public string SevenDown { get; set; }
        public string Collection { get; set; }
        public string CollectionCNS { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBSIZ { get; set; }
        public string RBNAM { get; set; }
        public Nullable<int> RBQTY { get; set; }
        public Nullable<decimal> RBDPC { get; set; }
        public Nullable<decimal> RBDCX { get; set; }
        public Nullable<decimal> RBUP1 { get; set; }
        public Nullable<decimal> RBAM1 { get; set; }
        public Nullable<decimal> PremiumCosts { get; set; }
        public Nullable<decimal> PremiumSum { get; set; }
        public Nullable<decimal> DayPerformance { get; set; }
        public Nullable<decimal> CashPerformance { get; set; }
        public Nullable<decimal> ReimbursementPerformance { get; set; }
        public Nullable<decimal> CollectionPerformance { get; set; }
        public string RBCSR { get; set; }
        public string RBRER { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string RBRMA { get; set; }
        public Nullable<decimal> DrawnRatio { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
    
        public virtual DailyWorkA DailyWorkA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyWorkC> DailyWorkCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyWorkD> DailyWorkDs { get; set; }
    }
}
