//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCalendar
    {
        public int EventCalendarKey { get; set; }
        public string EventTitle { get; set; }
        public string EventKind { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> EventStartDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string EventPlace { get; set; }
        public string JoinCriteria { get; set; }
        public string EventContent { get; set; }
        public string EventFee { get; set; }
        public string ContactInfo { get; set; }
        public string Speaker { get; set; }
        public string remark { get; set; }
        public string Attatchment { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
        public string UpdateUser { get; set; }
    }
}
