//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderAD
    {
        public int ADKey { get; set; }
        public string ADName { get; set; }
        public string ImageURL { get; set; }
        public string ImageFile { get; set; }
        public string CompanyNo { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> Impressions { get; set; }
        public string TargetUrl { get; set; }
        public string TargetType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Post { get; set; }
        public string Remark { get; set; }
        public string ADType { get; set; }
    }
}
