//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCategoryDescription
    {
        public string CategoryID { get; set; }
        public string CultureInfo { get; set; }
        public string CategoryShortName { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryPicture { get; set; }
    }
}
