//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETBWSA
    {
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string BSPRJ { get; set; }
        public string BSVER { get; set; }
        public string BSTBN { get; set; }
        public string BSTBC { get; set; }
        public string BSDIR { get; set; }
        public string BSUNT { get; set; }
        public string BSFRM { get; set; }
        public string BSWHE { get; set; }
        public string BSDOC { get; set; }
        public string ShowReport { get; set; }
        public Nullable<int> ColsPerRow { get; set; }
        public string Script { get; set; }
    }
}
