//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETBWSB
    {
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string BSPRJ { get; set; }
        public string BSVER { get; set; }
        public string BSTBN { get; set; }
        public string BSUNT { get; set; }
        public string BSITM { get; set; }
        public string BSFLN { get; set; }
        public string BSTXT { get; set; }
        public string BSCNM { get; set; }
        public string BSFTP { get; set; }
        public Nullable<double> BSLEN { get; set; }
        public string BSDMK { get; set; }
        public string BSIMK { get; set; }
        public string BSJOT { get; set; }
        public string BSJT1 { get; set; }
        public string BSJOF { get; set; }
        public string BSIPC { get; set; }
        public string BSSEC { get; set; }
        public string BSREP { get; set; }
        public string BSKEY { get; set; }
        public string BSDUP { get; set; }
        public string BSRGE { get; set; }
        public string BSMAX { get; set; }
        public string BSMIN { get; set; }
        public string BSATN { get; set; }
        public string BSATM { get; set; }
        public string BSISI { get; set; }
        public string BSISM { get; set; }
        public string BSISE { get; set; }
        public string BSSER { get; set; }
        public string BSISS { get; set; }
        public string BSFLS { get; set; }
        public string BSFNS { get; set; }
        public string BSFWS { get; set; }
        public string BSSQL { get; set; }
        public string BSDEF { get; set; }
        public string BSIST { get; set; }
        public string BSULC { get; set; }
        public string BSIQE { get; set; }
        public string BSICP { get; set; }
        public string BSIOJ { get; set; }
        public Nullable<decimal> BSORD { get; set; }
        public string BSISK { get; set; }
        public string BSALN { get; set; }
        public string BSRMK { get; set; }
        public string BSRM1 { get; set; }
        public string WhereStr { get; set; }
        public string IsALL { get; set; }
        public string IsOrderBy { get; set; }
        public string OrderBy { get; set; }
        public string DialogWidth { get; set; }
        public string DialogURL { get; set; }
        public string OnBlur { get; set; }
        public string LayoutID { get; set; }
        public Nullable<int> LayoutRow { get; set; }
        public Nullable<int> LayoutCol { get; set; }
        public Nullable<int> LayoutColSpan { get; set; }
        public string onkeypress { get; set; }
        public string onchange { get; set; }
        public string onfocus { get; set; }
        public string onclick { get; set; }
        public string IsLabel { get; set; }
        public string RepeatDirection { get; set; }
        public string IsBlank { get; set; }
        public string DataField { get; set; }
    }
}
