//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewBonusIWC
    {
        public string BSYMM { get; set; }
        public string BSNUM { get; set; }
        public Nullable<decimal> BSFEAT { get; set; }
        public Nullable<decimal> BSGET { get; set; }
        public Nullable<decimal> BSGRN { get; set; }
        public Nullable<decimal> BSALC { get; set; }
        public Nullable<decimal> BSADD { get; set; }
        public Nullable<decimal> BSSUB { get; set; }
        public Nullable<decimal> BSAD2 { get; set; }
        public Nullable<decimal> BSSU2 { get; set; }
        public Nullable<decimal> ShiftDeduction { get; set; }
        public Nullable<decimal> MPLUS1 { get; set; }
        public Nullable<decimal> MPLUS2 { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> Welfare { get; set; }
        public Nullable<decimal> CourtDeduction { get; set; }
    }
}
