//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationObject
    {
        public string OrgNo { get; set; }
        public string CompanyName { get; set; }
        public string RegionNo { get; set; }
        public string CompanyNames { get; set; }
        public string VatNo { get; set; }
        public string RealVatNo { get; set; }
        public string ChargePerson { get; set; }
        public string Address1 { get; set; }
        public string ContactPerson { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactExt { get; set; }
        public string FaxNo { get; set; }
        public string URL { get; set; }
        public string ApproveTradeType { get; set; }
        public string ApproveStatus { get; set; }
        public string GroupBelong { get; set; }
    }
}
