//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSZWA
    {
        public string RAREN { get; set; }
        public string RACNS { get; set; }
        public Nullable<int> RAQT1 { get; set; }
        public Nullable<decimal> RATO1 { get; set; }
        public Nullable<int> RAQT2 { get; set; }
        public Nullable<decimal> RATO2 { get; set; }
        public string PERIOD { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public Nullable<System.DateTime> RADAT { get; set; }
    }
}
