//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSZWB
    {
        public string RBREN { get; set; }
        public string BSCNS { get; set; }
        public string BSNCR { get; set; }
        public string BSNAM { get; set; }
        public Nullable<decimal> BSEEP { get; set; }
        public string BSSTA { get; set; }
        public Nullable<int> BSQQY { get; set; }
        public Nullable<int> BSTOM { get; set; }
        public Nullable<int> AVQTA { get; set; }
        public Nullable<int> AVQTB { get; set; }
        public Nullable<double> RATEA { get; set; }
        public Nullable<double> RATEB { get; set; }
        public string BCLAN { get; set; }
        public Nullable<int> BSQT2 { get; set; }
        public string BSNA2 { get; set; }
        public Nullable<int> BSLEV { get; set; }
        public Nullable<int> BSQTD { get; set; }
        public Nullable<int> PREQY { get; set; }
        public string BSN22 { get; set; }
        public Nullable<int> POSQY { get; set; }
        public Nullable<int> ONROAD { get; set; }
        public Nullable<int> UNGET { get; set; }
        public Nullable<int> PSQTY { get; set; }
        public Nullable<int> AJQTY { get; set; }
        public Nullable<int> SAPQY { get; set; }
        public Nullable<int> BSLIM { get; set; }
        public Nullable<int> SUPQY { get; set; }
        public Nullable<decimal> PSAMT { get; set; }
        public string RBFLG { get; set; }
        public string BSSTAnext { get; set; }
        public Nullable<int> BSQT2temp { get; set; }
    }
}
