//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseAllocateC
    {
        public string RCREN { get; set; }
        public string RBITM { get; set; }
        public string RCITM { get; set; }
        public string RCCNS { get; set; }
        public string RCRER { get; set; }
        public Nullable<int> RCQTY { get; set; }
        public string RCRE2 { get; set; }
    
        public virtual PurchaseAllocateA PurchaseAllocateA { get; set; }
    }
}
