//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public string Sno { get; set; }
        public string TableName { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string QueryTitle { get; set; }
        public string lb_ID1 { get; set; }
        public string lb_ID2 { get; set; }
        public string lb_ID3 { get; set; }
        public string lb_ID4 { get; set; }
        public string Condition { get; set; }
        public string Memo { get; set; }
        public string JoinCondition { get; set; }
        public string Field5 { get; set; }
        public string lb_ID5 { get; set; }
    }
}
