//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADAT
    {
        public System.DateTime RADAT1 { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<short> Month { get; set; }
        public Nullable<short> Day { get; set; }
        public string Quarter { get; set; }
        public string VYMM { get; set; }
    }
}
