//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBonusNSAL
    {
        public int RBKEY { get; set; }
        public string RBYMM { get; set; }
        public string RBENO { get; set; }
        public string RBTIT { get; set; }
        public string RBREN { get; set; }
        public string RBTYP { get; set; }
        public string RBCLS { get; set; }
        public Nullable<decimal> RBTGT { get; set; }
        public Nullable<decimal> RBREA { get; set; }
        public Nullable<decimal> RBTGTRAT { get; set; }
        public string RBCNS { get; set; }
        public string RBBCS { get; set; }
        public string RBITM { get; set; }
        public Nullable<decimal> RBAMT { get; set; }
        public Nullable<decimal> RBSALRAT { get; set; }
        public Nullable<decimal> RBWTVAL { get; set; }
        public Nullable<decimal> RBVAL { get; set; }
        public Nullable<int> RBCOUNT { get; set; }
        public Nullable<decimal> RBDAYRAT { get; set; }
        public Nullable<decimal> RBBAL { get; set; }
        public string TRUSR { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
    }
}
