//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDCGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RDCGA()
        {
            this.RDCGBs = new HashSet<RDCGB>();
        }
    
        public string RAREN { get; set; }
        public string RADKD { get; set; }
        public string RALEV { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public string RAMEN { get; set; }
        public string RADPT { get; set; }
        public Nullable<System.DateTime> RASTD { get; set; }
        public string RANAM { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public Nullable<System.DateTime> RADAT { get; set; }
        public string RAUSR { get; set; }
        public string TRMOD { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string RAForm { get; set; }
        public string RAClose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDCGB> RDCGBs { get; set; }
    }
}
