//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rinvoice
    {
        public string RANUM { get; set; }
        public string RANUMName { get; set; }
        public string RAYER { get; set; }
        public System.DateTime RADAY { get; set; }
        public string RACOS { get; set; }
        public string RAINV { get; set; }
        public string RACNS { get; set; }
        public string RAMEN { get; set; }
        public string RANUI { get; set; }
        public string RANAM { get; set; }
        public Nullable<int> RAQTY { get; set; }
        public Nullable<decimal> RADPC { get; set; }
        public Nullable<decimal> RAAMT { get; set; }
        public Nullable<decimal> RATAX { get; set; }
        public Nullable<decimal> RAAM1 { get; set; }
        public string RASAL { get; set; }
        public string RAFlow { get; set; }
        public string RAInvalid { get; set; }
        public string RARMA { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
    }
}
