//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RIRA()
        {
            this.RIRBs = new HashSet<RIRB>();
            this.RIRCs = new HashSet<RIRC>();
        }
    
        public string RAREN { get; set; }
        public System.DateTime RADAT { get; set; }
        public string RANUM { get; set; }
        public string RATRA { get; set; }
        public string RAMNY { get; set; }
        public Nullable<decimal> RARAT { get; set; }
        public string RAFOB { get; set; }
        public string RAHUB { get; set; }
        public string RARMK { get; set; }
        public string RAMEN { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public string RAIVO { get; set; }
        public Nullable<int> RAF05 { get; set; }
        public Nullable<double> RARA1 { get; set; }
        public Nullable<System.DateTime> RAEDT { get; set; }
        public Nullable<int> RATIM { get; set; }
        public Nullable<int> RATOT { get; set; }
        public Nullable<decimal> RATMT { get; set; }
        public Nullable<decimal> RATAX { get; set; }
        public Nullable<System.DateTime> RASTD { get; set; }
        public Nullable<System.DateTime> RAED2 { get; set; }
        public Nullable<decimal> RATIT { get; set; }
        public Nullable<double> RATIQ { get; set; }
        public string RARER { get; set; }
        public Nullable<decimal> RATXA { get; set; }
        public string RANU2 { get; set; }
        public Nullable<decimal> RATO2 { get; set; }
        public string RACS1 { get; set; }
        public string RACS2 { get; set; }
        public string RACNS { get; set; }
        public string RAYNM { get; set; }
        public string RACNM { get; set; }
        public Nullable<double> RAMRK { get; set; }
        public string RASEA { get; set; }
        public Nullable<decimal> RAMKR { get; set; }
        public string RAMKM { get; set; }
        public Nullable<System.DateTime> RAMDY { get; set; }
        public string RAMN1 { get; set; }
        public string RAPON { get; set; }
        public decimal RACMS { get; set; }
        public Nullable<decimal> RACMM { get; set; }
        public decimal RAHMS { get; set; }
        public Nullable<decimal> RAFRE { get; set; }
        public Nullable<decimal> RATXF { get; set; }
        public string RAINF { get; set; }
        public string RAALC { get; set; }
        public Nullable<int> RATIMnoZ1Z2 { get; set; }
    
        public virtual BCU BCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIRB> RIRBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RIRC> RIRCs { get; set; }
    }
}
