//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIRB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCOS { get; set; }
        public string RBPNR { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBCLZ { get; set; }
        public Nullable<decimal> RBUPC { get; set; }
        public Nullable<decimal> RBDCX { get; set; }
        public Nullable<int> RBQTY { get; set; }
        public Nullable<decimal> RBAMT { get; set; }
        public string RBCAR { get; set; }
        public string RBCTM { get; set; }
        public string RBRN1 { get; set; }
        public string RBRTM { get; set; }
        public Nullable<decimal> RBUPD { get; set; }
        public Nullable<decimal> RBAM1 { get; set; }
        public Nullable<double> RBMRK { get; set; }
        public Nullable<double> RBMPC { get; set; }
        public Nullable<double> RBUPF { get; set; }
        public Nullable<double> RBUPG { get; set; }
        public Nullable<double> RBDPC { get; set; }
        public Nullable<int> RBQTY01 { get; set; }
        public Nullable<int> RBQTY02 { get; set; }
        public Nullable<int> RBQTY03 { get; set; }
        public Nullable<int> RBQTY04 { get; set; }
        public Nullable<int> RBQTY05 { get; set; }
        public Nullable<int> RBQTY06 { get; set; }
        public Nullable<int> RBQTY07 { get; set; }
        public Nullable<int> RBQTY08 { get; set; }
        public Nullable<int> RBQTY09 { get; set; }
        public Nullable<int> RBQTY10 { get; set; }
        public Nullable<int> RBQTY11 { get; set; }
        public Nullable<int> RBQTY12 { get; set; }
        public Nullable<int> RBQTY13 { get; set; }
        public Nullable<int> RBQTY14 { get; set; }
        public Nullable<int> RBQTY15 { get; set; }
        public Nullable<int> RBQTY16 { get; set; }
        public Nullable<int> RBQTY17 { get; set; }
        public Nullable<int> RBQTY18 { get; set; }
        public Nullable<int> RBQTY19 { get; set; }
        public Nullable<int> RBQTY20 { get; set; }
        public Nullable<int> RBRQY { get; set; }
        public Nullable<int> RBRQY01 { get; set; }
        public Nullable<int> RBRQY02 { get; set; }
        public Nullable<int> RBRQY03 { get; set; }
        public Nullable<int> RBRQY04 { get; set; }
        public Nullable<int> RBRQY05 { get; set; }
        public Nullable<int> RBRQY06 { get; set; }
        public Nullable<int> RBRQY07 { get; set; }
        public Nullable<int> RBRQY08 { get; set; }
        public Nullable<int> RBRQY09 { get; set; }
        public Nullable<int> RBRQY10 { get; set; }
        public Nullable<int> RBRQY11 { get; set; }
        public Nullable<int> RBRQY12 { get; set; }
        public Nullable<int> RBRQY13 { get; set; }
        public Nullable<int> RBRQY14 { get; set; }
        public Nullable<int> RBRQY15 { get; set; }
        public Nullable<int> RBRQY16 { get; set; }
        public Nullable<int> RBRQY17 { get; set; }
        public Nullable<int> RBRQY18 { get; set; }
        public Nullable<int> RBRQY19 { get; set; }
        public Nullable<int> RBRQY20 { get; set; }
        public Nullable<int> RBQTY21 { get; set; }
        public Nullable<int> RBQTY22 { get; set; }
        public Nullable<int> RBQTY23 { get; set; }
        public Nullable<int> RBQTY24 { get; set; }
        public Nullable<int> RBQTY25 { get; set; }
        public Nullable<int> RBQTY26 { get; set; }
        public Nullable<int> RBQTY27 { get; set; }
        public Nullable<int> RBQTY28 { get; set; }
        public Nullable<int> RBQTY29 { get; set; }
        public Nullable<int> RBQTY30 { get; set; }
        public Nullable<int> RBRQY21 { get; set; }
        public Nullable<int> RBRQY22 { get; set; }
        public Nullable<int> RBRQY23 { get; set; }
        public Nullable<int> RBRQY24 { get; set; }
        public Nullable<int> RBRQY25 { get; set; }
        public Nullable<int> RBRQY26 { get; set; }
        public Nullable<int> RBRQY27 { get; set; }
        public Nullable<int> RBRQY28 { get; set; }
        public Nullable<int> RBRQY29 { get; set; }
        public Nullable<int> RBRQY30 { get; set; }
        public Nullable<decimal> RBTCX { get; set; }
        public string RBRMK { get; set; }
        public Nullable<decimal> RBEEP { get; set; }
        public Nullable<decimal> RBCTR { get; set; }
        public Nullable<double> RBCTD { get; set; }
        public string RBUIW { get; set; }
    
        public virtual RIRA RIRA { get; set; }
    }
}
