//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RISD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RISD()
        {
            this.RISEs = new HashSet<RISE>();
        }
    
        public string RDLCN { get; set; }
        public Nullable<double> RDFOB { get; set; }
        public Nullable<double> RDRAT { get; set; }
        public Nullable<double> RDT01 { get; set; }
        public Nullable<double> RDT02 { get; set; }
        public Nullable<double> RDT03 { get; set; }
        public Nullable<double> RDDCX { get; set; }
        public Nullable<double> RDAMT { get; set; }
        public Nullable<double> RDTNT { get; set; }
        public Nullable<double> RDT04 { get; set; }
        public Nullable<double> RDT05 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RISE> RISEs { get; set; }
    }
}
