//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPCP
    {
        public string RSREN { get; set; }
        public string RSENO { get; set; }
        public string RSDPO { get; set; }
        public string RSDPT { get; set; }
        public string RSSVR { get; set; }
        public string RSDP3 { get; set; }
        public string RSDP4 { get; set; }
        public Nullable<System.DateTime> RSDAT { get; set; }
        public Nullable<System.DateTime> RSDA1 { get; set; }
        public string RSCLS { get; set; }
        public string RSTM1 { get; set; }
        public string RSTM2 { get; set; }
        public Nullable<double> RSHUR { get; set; }
        public Nullable<int> RSANN { get; set; }
        public string RSDOC { get; set; }
        public string RSMEN { get; set; }
        public string RSREX { get; set; }
        public string RSRMK { get; set; }
        public string RSVSR { get; set; }
        public Nullable<System.DateTime> RSVDT { get; set; }
        public string RSVS1 { get; set; }
        public string RSVS2 { get; set; }
        public Nullable<System.DateTime> RSVD1 { get; set; }
        public Nullable<System.DateTime> RSVD2 { get; set; }
        public string RSCL1 { get; set; }
        public Nullable<double> RSHU1 { get; set; }
        public Nullable<System.DateTime> RSDA2 { get; set; }
        public string RSPPT { get; set; }
        public string FuneralQualifications { get; set; }
        public string FuneralName { get; set; }
        public string BirthQualifications { get; set; }
        public Nullable<int> BirthTimes { get; set; }
        public string RSCL2 { get; set; }
        public string RSCLV { get; set; }
        public string RSCLVRMK { get; set; }
    }
}
