//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptMonthCatalogStock
    {
        public Nullable<decimal> SNo { get; set; }
        public string RACNS { get; set; }
        public string Class1 { get; set; }
        public string Class1Name { get; set; }
        public string Class2 { get; set; }
        public string Class2Name { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string Kind { get; set; }
        public string RptGroup2 { get; set; }
        public int Id { get; set; }
    }
}
