//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQSMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RQSMA()
        {
            this.RQSMBs = new HashSet<RQSMB>();
        }
    
        public string RAREN { get; set; }
        public string RACLS { get; set; }
        public Nullable<System.DateTime> RADAT { get; set; }
        public string RAUSR { get; set; }
        public string RAUDP { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public string RAMEN { get; set; }
        public string RADPT { get; set; }
        public Nullable<System.DateTime> RADOS { get; set; }
        public Nullable<System.DateTime> RADOE { get; set; }
        public string RANAM { get; set; }
        public string RAPPS { get; set; }
        public string RARMK { get; set; }
        public Nullable<System.DateTime> RACDT { get; set; }
        public string RACUR { get; set; }
        public string RACKD { get; set; }
        public string TRMOD { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string RACQR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQSMB> RQSMBs { get; set; }
    }
}
