//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQSNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RQSNA()
        {
            this.RQSNBs = new HashSet<RQSNB>();
            this.RQSNCs = new HashSet<RQSNC>();
        }
    
        public string RAREN { get; set; }
        public string RARER { get; set; }
        public string RACLS { get; set; }
        public Nullable<System.DateTime> RADAT { get; set; }
        public string RAUSR { get; set; }
        public string RAUDP { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public string RAMEN { get; set; }
        public string RADPT { get; set; }
        public string RANAM { get; set; }
        public string RAPPS { get; set; }
        public string RAASA { get; set; }
        public string RAAAN { get; set; }
        public string RARMK { get; set; }
        public string TRMOD { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string RASBT { get; set; }
        public Nullable<System.DateTime> RADAC { get; set; }
        public string RACER { get; set; }
        public string RACTM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQSNB> RQSNBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RQSNC> RQSNCs { get; set; }
    }
}
