//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSDB
    {
        public string RBREN { get; set; }
        public Nullable<System.DateTime> RBDAY { get; set; }
        public string RBTYP { get; set; }
        public Nullable<decimal> RBDIM { get; set; }
        public string RBGRE { get; set; }
        public string RBDC0 { get; set; }
        public Nullable<double> RBDCX { get; set; }
        public Nullable<double> RBAMT { get; set; }
        public Nullable<double> RBAM1 { get; set; }
        public Nullable<double> RBAM2 { get; set; }
        public Nullable<double> RBAM3 { get; set; }
        public Nullable<double> RBAM4 { get; set; }
        public string RBSET { get; set; }
        public string RBREV { get; set; }
        public string RQREN { get; set; }
        public string RBCS1 { get; set; }
        public string RBITM { get; set; }
    
        public virtual RSDA RSDA { get; set; }
    }
}
