//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSEB
    {
        public string RBREN { get; set; }
        public int RBITM { get; set; }
        public Nullable<System.DateTime> RBDAY { get; set; }
        public string RBPAY { get; set; }
        public Nullable<double> RBAMT { get; set; }
        public Nullable<double> RBTAX { get; set; }
        public string RBCLS { get; set; }
        public string RBTXT { get; set; }
    
        public virtual RSEA RSEA { get; set; }
    }
}
