//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIAB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCNS { get; set; }
        public string RBCN2 { get; set; }
        public string RBOEN { get; set; }
        public string RBOTM { get; set; }
        public string RBCLS { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBCSR { get; set; }
        public string RBRER { get; set; }
        public string RBIEM { get; set; }
        public string RBCAR { get; set; }
        public string RBCIM { get; set; }
        public string RBRRE { get; set; }
        public string RBRIT { get; set; }
        public string RBPTN { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBUNI { get; set; }
        public Nullable<double> RBDC1 { get; set; }
        public Nullable<double> RBQTY { get; set; }
        public Nullable<double> RBQTP { get; set; }
        public Nullable<decimal> RBDPC { get; set; }
        public Nullable<decimal> RBUP1 { get; set; }
        public Nullable<decimal> RBUPC { get; set; }
        public Nullable<int> RBDCX { get; set; }
        public Nullable<decimal> RBAM1 { get; set; }
        public Nullable<decimal> RBAMT { get; set; }
        public Nullable<double> RBCOT { get; set; }
        public string RBREV { get; set; }
        public string RBPRT { get; set; }
        public string RBRMK { get; set; }
        public string RBRBN { get; set; }
        public string RBBTM { get; set; }
        public string RBRE1 { get; set; }
        public string RBCTP { get; set; }
        public Nullable<double> RBUP2 { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string RBFG1 { get; set; }
        public string RBFG2 { get; set; }
        public string RBCLZ { get; set; }
        public Nullable<double> RBQTY01 { get; set; }
        public Nullable<double> RBQTY02 { get; set; }
        public Nullable<double> RBQTY03 { get; set; }
        public Nullable<double> RBQTY04 { get; set; }
        public Nullable<double> RBQTY05 { get; set; }
        public Nullable<double> RBQTY06 { get; set; }
        public Nullable<double> RBQTY07 { get; set; }
        public Nullable<double> RBQTY08 { get; set; }
        public Nullable<double> RBQTY09 { get; set; }
        public Nullable<double> RBQTY10 { get; set; }
        public Nullable<double> RBQTY11 { get; set; }
        public Nullable<double> RBQTY12 { get; set; }
        public Nullable<double> RBQTY13 { get; set; }
        public Nullable<double> RBQTY14 { get; set; }
        public Nullable<double> RBQTY15 { get; set; }
        public Nullable<double> RBQTY16 { get; set; }
        public Nullable<double> RBQTY17 { get; set; }
        public Nullable<double> RBQTY18 { get; set; }
        public Nullable<double> RBQTY19 { get; set; }
        public Nullable<double> RBQTY20 { get; set; }
        public Nullable<double> RBQTP01 { get; set; }
        public Nullable<double> RBQTP02 { get; set; }
        public Nullable<double> RBQTP03 { get; set; }
        public Nullable<double> RBQTP04 { get; set; }
        public Nullable<double> RBQTP05 { get; set; }
        public Nullable<double> RBQTP06 { get; set; }
        public Nullable<double> RBQTP07 { get; set; }
        public Nullable<double> RBQTP08 { get; set; }
        public Nullable<double> RBQTP09 { get; set; }
        public Nullable<double> RBQTP10 { get; set; }
        public Nullable<double> RBQTP11 { get; set; }
        public Nullable<double> RBQTP12 { get; set; }
        public Nullable<double> RBQTP13 { get; set; }
        public Nullable<double> RBQTP14 { get; set; }
        public Nullable<double> RBQTP15 { get; set; }
        public Nullable<double> RBQTP16 { get; set; }
        public Nullable<double> RBQTP17 { get; set; }
        public Nullable<double> RBQTP18 { get; set; }
        public Nullable<double> RBQTP19 { get; set; }
        public Nullable<double> RBQTP20 { get; set; }
        public Nullable<double> RBAQY { get; set; }
        public Nullable<double> RBAQY01 { get; set; }
        public Nullable<double> RBAQY02 { get; set; }
        public Nullable<double> RBAQY03 { get; set; }
        public Nullable<double> RBAQY04 { get; set; }
        public Nullable<double> RBAQY05 { get; set; }
        public Nullable<double> RBAQY06 { get; set; }
        public Nullable<double> RBAQY07 { get; set; }
        public Nullable<double> RBAQY08 { get; set; }
        public Nullable<double> RBAQY09 { get; set; }
        public Nullable<double> RBAQY10 { get; set; }
        public Nullable<double> RBAQY11 { get; set; }
        public Nullable<double> RBAQY12 { get; set; }
        public Nullable<double> RBAQY13 { get; set; }
        public Nullable<double> RBAQY14 { get; set; }
        public Nullable<double> RBAQY15 { get; set; }
        public Nullable<double> RBAQY16 { get; set; }
        public Nullable<double> RBAQY17 { get; set; }
        public Nullable<double> RBAQY18 { get; set; }
        public Nullable<double> RBAQY19 { get; set; }
        public Nullable<double> RBAQY20 { get; set; }
        public Nullable<double> RBQTY21 { get; set; }
        public Nullable<double> RBQTY22 { get; set; }
        public Nullable<double> RBQTY23 { get; set; }
        public Nullable<double> RBQTY24 { get; set; }
        public Nullable<double> RBQTY25 { get; set; }
        public Nullable<double> RBQTY26 { get; set; }
        public Nullable<double> RBQTY27 { get; set; }
        public Nullable<double> RBQTY28 { get; set; }
        public Nullable<double> RBQTY29 { get; set; }
        public Nullable<double> RBQTY30 { get; set; }
        public Nullable<double> RBQTP21 { get; set; }
        public Nullable<double> RBQTP22 { get; set; }
        public Nullable<double> RBQTP23 { get; set; }
        public Nullable<double> RBQTP24 { get; set; }
        public Nullable<double> RBQTP25 { get; set; }
        public Nullable<double> RBQTP26 { get; set; }
        public Nullable<double> RBQTP27 { get; set; }
        public Nullable<double> RBQTP28 { get; set; }
        public Nullable<double> RBQTP29 { get; set; }
        public Nullable<double> RBQTP30 { get; set; }
        public Nullable<double> RBAQY21 { get; set; }
        public Nullable<double> RBAQY22 { get; set; }
        public Nullable<double> RBAQY23 { get; set; }
        public Nullable<double> RBAQY24 { get; set; }
        public Nullable<double> RBAQY25 { get; set; }
        public Nullable<double> RBAQY26 { get; set; }
        public Nullable<double> RBAQY27 { get; set; }
        public Nullable<double> RBAQY28 { get; set; }
        public Nullable<double> RBAQY29 { get; set; }
        public Nullable<double> RBAQY30 { get; set; }
    
        public virtual BSTL BSTL { get; set; }
        public virtual RSIAA RSIAA { get; set; }
    }
}
