//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIHB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCNS { get; set; }
        public string RBCLS { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBCSR { get; set; }
        public string RBRER { get; set; }
        public string RBIEM { get; set; }
        public string RBCAR { get; set; }
        public string RBCIM { get; set; }
        public string RBONU { get; set; }
        public string RBPTN { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBUNI { get; set; }
        public Nullable<double> RBDC1 { get; set; }
        public string RBCLZ { get; set; }
        public string RBITZ { get; set; }
        public string RBSIZ { get; set; }
        public Nullable<int> RBQTY { get; set; }
        public Nullable<int> RBQTP { get; set; }
        public Nullable<int> RBQTS { get; set; }
        public Nullable<double> RBDPC { get; set; }
        public Nullable<double> RBUP1 { get; set; }
        public Nullable<double> RBUPC { get; set; }
        public Nullable<double> RBDCX { get; set; }
        public Nullable<double> RBAM1 { get; set; }
        public Nullable<double> RBAMT { get; set; }
        public Nullable<double> RBCOT { get; set; }
        public string RBREV { get; set; }
        public string RBPRT { get; set; }
        public string RBRMK { get; set; }
        public string RBCTP { get; set; }
        public Nullable<double> RBUP2 { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string RBFG1 { get; set; }
        public string RBFG2 { get; set; }
        public string RBTOY { get; set; }
    
        public virtual BSTO BSTO { get; set; }
        public virtual RSIHA RSIHA { get; set; }
    }
}
