//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSIIA()
        {
            this.RSIIBs = new HashSet<RSIIB>();
        }
    
        public string RACNS { get; set; }
        public System.DateTime RADAY { get; set; }
        public string RASER { get; set; }
        public string RANUM { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string RAMEN { get; set; }
        public string RAREN { get; set; }
        public string RARMK { get; set; }
        public string RSIMN { get; set; }
        public Nullable<System.DateTime> RAXDT { get; set; }
        public string TRUSR { get; set; }
    
        public virtual BCU BCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIIB> RSIIBs { get; set; }
    }
}
