//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIMB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCNS { get; set; }
        public string RBCN2 { get; set; }
        public string RBOEN { get; set; }
        public string RBOTM { get; set; }
        public string RBCLS { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBCSR { get; set; }
        public string RBRER { get; set; }
        public string RBIEM { get; set; }
        public string RBIEC { get; set; }
        public string RBCAR { get; set; }
        public string RBCIM { get; set; }
        public string RBPTN { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBUNI { get; set; }
        public Nullable<double> RBDC1 { get; set; }
        public Nullable<double> RBQTY { get; set; }
        public Nullable<double> RBRQY { get; set; }
        public Nullable<double> RBCQY { get; set; }
        public Nullable<double> RBFQY { get; set; }
        public Nullable<double> RBDPC { get; set; }
        public Nullable<double> RBUP1 { get; set; }
        public Nullable<double> RBUPC { get; set; }
        public Nullable<double> RBDCX { get; set; }
        public Nullable<double> RBAM1 { get; set; }
        public Nullable<double> RBAMT { get; set; }
        public Nullable<double> RBCOT { get; set; }
        public string RBREV { get; set; }
        public string RBPRT { get; set; }
        public string RBRMK { get; set; }
        public string RBRBN { get; set; }
        public string RBBTM { get; set; }
        public string RBRE1 { get; set; }
        public string RBCTP { get; set; }
        public Nullable<double> RBUP2 { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string RBFG1 { get; set; }
        public string RBFG2 { get; set; }
        public string RBCLZ { get; set; }
        public Nullable<double> RBQTY01 { get; set; }
        public Nullable<double> RBQTY02 { get; set; }
        public Nullable<double> RBQTY03 { get; set; }
        public Nullable<double> RBQTY04 { get; set; }
        public Nullable<double> RBQTY05 { get; set; }
        public Nullable<double> RBQTY06 { get; set; }
        public Nullable<double> RBQTY07 { get; set; }
        public Nullable<double> RBQTY08 { get; set; }
        public Nullable<double> RBQTY09 { get; set; }
        public Nullable<double> RBQTY10 { get; set; }
        public Nullable<double> RBQTY11 { get; set; }
        public Nullable<double> RBQTY12 { get; set; }
        public Nullable<double> RBQTY13 { get; set; }
        public Nullable<double> RBQTY14 { get; set; }
        public Nullable<double> RBQTY15 { get; set; }
        public Nullable<double> RBQTY16 { get; set; }
        public Nullable<double> RBQTY17 { get; set; }
        public Nullable<double> RBQTY18 { get; set; }
        public Nullable<double> RBQTY19 { get; set; }
        public Nullable<double> RBQTY20 { get; set; }
        public Nullable<double> RBRQY01 { get; set; }
        public Nullable<double> RBRQY02 { get; set; }
        public Nullable<double> RBRQY03 { get; set; }
        public Nullable<double> RBRQY04 { get; set; }
        public Nullable<double> RBRQY05 { get; set; }
        public Nullable<double> RBRQY06 { get; set; }
        public Nullable<double> RBRQY07 { get; set; }
        public Nullable<double> RBRQY08 { get; set; }
        public Nullable<double> RBRQY09 { get; set; }
        public Nullable<double> RBRQY10 { get; set; }
        public Nullable<double> RBRQY11 { get; set; }
        public Nullable<double> RBRQY12 { get; set; }
        public Nullable<double> RBRQY13 { get; set; }
        public Nullable<double> RBRQY14 { get; set; }
        public Nullable<double> RBRQY15 { get; set; }
        public Nullable<double> RBRQY16 { get; set; }
        public Nullable<double> RBRQY17 { get; set; }
        public Nullable<double> RBRQY18 { get; set; }
        public Nullable<double> RBRQY19 { get; set; }
        public Nullable<double> RBRQY20 { get; set; }
        public Nullable<double> RBCQY01 { get; set; }
        public Nullable<double> RBCQY02 { get; set; }
        public Nullable<double> RBCQY03 { get; set; }
        public Nullable<double> RBCQY04 { get; set; }
        public Nullable<double> RBCQY05 { get; set; }
        public Nullable<double> RBCQY06 { get; set; }
        public Nullable<double> RBCQY07 { get; set; }
        public Nullable<double> RBCQY08 { get; set; }
        public Nullable<double> RBCQY09 { get; set; }
        public Nullable<double> RBCQY10 { get; set; }
        public Nullable<double> RBCQY11 { get; set; }
        public Nullable<double> RBCQY12 { get; set; }
        public Nullable<double> RBCQY13 { get; set; }
        public Nullable<double> RBCQY14 { get; set; }
        public Nullable<double> RBCQY15 { get; set; }
        public Nullable<double> RBCQY16 { get; set; }
        public Nullable<double> RBCQY17 { get; set; }
        public Nullable<double> RBCQY18 { get; set; }
        public Nullable<double> RBCQY19 { get; set; }
        public Nullable<double> RBCQY20 { get; set; }
        public Nullable<double> RBQTY21 { get; set; }
        public Nullable<double> RBQTY22 { get; set; }
        public Nullable<double> RBQTY23 { get; set; }
        public Nullable<double> RBQTY24 { get; set; }
        public Nullable<double> RBQTY25 { get; set; }
        public Nullable<double> RBQTY26 { get; set; }
        public Nullable<double> RBQTY27 { get; set; }
        public Nullable<double> RBQTY28 { get; set; }
        public Nullable<double> RBQTY29 { get; set; }
        public Nullable<double> RBQTY30 { get; set; }
        public Nullable<double> RBRQY21 { get; set; }
        public Nullable<double> RBRQY22 { get; set; }
        public Nullable<double> RBRQY23 { get; set; }
        public Nullable<double> RBRQY24 { get; set; }
        public Nullable<double> RBRQY25 { get; set; }
        public Nullable<double> RBRQY26 { get; set; }
        public Nullable<double> RBRQY27 { get; set; }
        public Nullable<double> RBRQY28 { get; set; }
        public Nullable<double> RBRQY29 { get; set; }
        public Nullable<double> RBRQY30 { get; set; }
        public Nullable<double> RBCQY21 { get; set; }
        public Nullable<double> RBCQY22 { get; set; }
        public Nullable<double> RBCQY23 { get; set; }
        public Nullable<double> RBCQY24 { get; set; }
        public Nullable<double> RBCQY25 { get; set; }
        public Nullable<double> RBCQY26 { get; set; }
        public Nullable<double> RBCQY27 { get; set; }
        public Nullable<double> RBCQY28 { get; set; }
        public Nullable<double> RBCQY29 { get; set; }
        public Nullable<double> RBCQY30 { get; set; }
        public string SENCR { get; set; }
    
        public virtual BSTL BSTL { get; set; }
        public virtual RSIMA RSIMA { get; set; }
    }
}
