//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIOB
    {
        public string ROREN { get; set; }
        public string ROITM { get; set; }
        public string ROCNS { get; set; }
        public string ROCN2 { get; set; }
        public string ROOEN { get; set; }
        public string ROOTM { get; set; }
        public string ROCLS { get; set; }
        public string ROCOS { get; set; }
        public string ROCTS { get; set; }
        public string ROCSR { get; set; }
        public string RORER { get; set; }
        public string ROIEM { get; set; }
        public string ROCAR { get; set; }
        public string ROCIM { get; set; }
        public string ROPTN { get; set; }
        public string RONCR { get; set; }
        public string ROCLR { get; set; }
        public string ROUNI { get; set; }
        public Nullable<double> RODC1 { get; set; }
        public Nullable<double> ROQTY { get; set; }
        public Nullable<double> ROQTP { get; set; }
        public Nullable<double> RODPC { get; set; }
        public Nullable<double> ROUP1 { get; set; }
        public Nullable<double> ROUPC { get; set; }
        public Nullable<double> RODCX { get; set; }
        public Nullable<double> ROAM1 { get; set; }
        public Nullable<double> ROAMT { get; set; }
        public Nullable<double> ROCOT { get; set; }
        public string ROREV { get; set; }
        public string ROPRT { get; set; }
        public string RORMK { get; set; }
        public string RORBN { get; set; }
        public string ROBTM { get; set; }
        public string RORE1 { get; set; }
        public string ROCTP { get; set; }
        public Nullable<double> ROUP2 { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string ROFG1 { get; set; }
        public string ROFG2 { get; set; }
        public string BSCLS { get; set; }
        public Nullable<double> ROQTY01 { get; set; }
        public Nullable<double> ROQTY02 { get; set; }
        public Nullable<double> ROQTY03 { get; set; }
        public Nullable<double> ROQTY04 { get; set; }
        public Nullable<double> ROQTY05 { get; set; }
        public Nullable<double> ROQTY06 { get; set; }
        public Nullable<double> ROQTY07 { get; set; }
        public Nullable<double> ROQTY08 { get; set; }
        public Nullable<double> ROQTY09 { get; set; }
        public Nullable<double> ROQTY10 { get; set; }
        public Nullable<double> ROQTY11 { get; set; }
        public Nullable<double> ROQTY12 { get; set; }
        public Nullable<double> ROQTY13 { get; set; }
        public Nullable<double> ROQTY14 { get; set; }
        public Nullable<double> ROQTY15 { get; set; }
        public Nullable<double> ROQTY16 { get; set; }
        public Nullable<double> ROQTY17 { get; set; }
        public Nullable<double> ROQTY18 { get; set; }
        public Nullable<double> ROQTY19 { get; set; }
        public Nullable<double> ROQTY20 { get; set; }
        public Nullable<double> ROQTP01 { get; set; }
        public Nullable<double> ROQTP02 { get; set; }
        public Nullable<double> ROQTP03 { get; set; }
        public Nullable<double> ROQTP04 { get; set; }
        public Nullable<double> ROQTP05 { get; set; }
        public Nullable<double> ROQTP06 { get; set; }
        public Nullable<double> ROQTP07 { get; set; }
        public Nullable<double> ROQTP08 { get; set; }
        public Nullable<double> ROQTP09 { get; set; }
        public Nullable<double> ROQTP10 { get; set; }
        public Nullable<double> ROQTP11 { get; set; }
        public Nullable<double> ROQTP12 { get; set; }
        public Nullable<double> ROQTP13 { get; set; }
        public Nullable<double> ROQTP14 { get; set; }
        public Nullable<double> ROQTP15 { get; set; }
        public Nullable<double> ROQTP16 { get; set; }
        public Nullable<double> ROQTP17 { get; set; }
        public Nullable<double> ROQTP18 { get; set; }
        public Nullable<double> ROQTP19 { get; set; }
        public Nullable<double> ROQTP20 { get; set; }
        public Nullable<double> ROQTY21 { get; set; }
        public Nullable<double> ROQTY22 { get; set; }
        public Nullable<double> ROQTY23 { get; set; }
        public Nullable<double> ROQTY24 { get; set; }
        public Nullable<double> ROQTY25 { get; set; }
        public Nullable<double> ROQTY26 { get; set; }
        public Nullable<double> ROQTY27 { get; set; }
        public Nullable<double> ROQTY28 { get; set; }
        public Nullable<double> ROQTY29 { get; set; }
        public Nullable<double> ROQTY30 { get; set; }
        public Nullable<double> ROQTP21 { get; set; }
        public Nullable<double> ROQTP22 { get; set; }
        public Nullable<double> ROQTP23 { get; set; }
        public Nullable<double> ROQTP24 { get; set; }
        public Nullable<double> ROQTP25 { get; set; }
        public Nullable<double> ROQTP26 { get; set; }
        public Nullable<double> ROQTP27 { get; set; }
        public Nullable<double> ROQTP28 { get; set; }
        public Nullable<double> ROQTP29 { get; set; }
        public Nullable<double> ROQTP30 { get; set; }
    }
}
