//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIOA
    {
        public string ROREN { get; set; }
        public string ROCNS { get; set; }
        public string ROCN2 { get; set; }
        public string ROOEN { get; set; }
        public string RONUM { get; set; }
        public string ROSHP { get; set; }
        public string ROCLS { get; set; }
        public string ROCTS { get; set; }
        public Nullable<System.DateTime> RODAY { get; set; }
        public Nullable<System.DateTime> RODAV { get; set; }
        public string ROINV { get; set; }
        public string RORMA { get; set; }
        public string ROMEN { get; set; }
        public string ROSAL { get; set; }
        public Nullable<System.DateTime> ROEDT { get; set; }
        public string ROCSR { get; set; }
        public string RORER { get; set; }
        public string ROCAR { get; set; }
        public string ROCS1 { get; set; }
        public string ROCS2 { get; set; }
        public Nullable<double> ROTAX { get; set; }
        public Nullable<double> ROTOL { get; set; }
        public string ROVIP { get; set; }
        public string ROMN3 { get; set; }
        public string ROADR { get; set; }
        public Nullable<double> ROAMR { get; set; }
        public string ROTEL { get; set; }
        public Nullable<System.DateTime> ROSDT { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
    }
}
