//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIQB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCNS { get; set; }
        public string RBCN2 { get; set; }
        public string RBCLS { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBONU { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBCLZ { get; set; }
        public string RBSIZ { get; set; }
        public Nullable<int> RBQTY { get; set; }
        public Nullable<decimal> RBDPC { get; set; }
        public Nullable<decimal> RBUP1 { get; set; }
        public Nullable<decimal> RBUPC { get; set; }
        public Nullable<decimal> RBDCX { get; set; }
        public string RBDC2 { get; set; }
        public Nullable<decimal> RBAM1 { get; set; }
        public Nullable<decimal> RBAMT { get; set; }
        public string RBRER { get; set; }
        public string RBRBN { get; set; }
        public string RBBTM { get; set; }
        public string RBRE1 { get; set; }
        public string RBCTP { get; set; }
        public Nullable<double> RBUP2 { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string RBRMA { get; set; }
        public Nullable<decimal> RBAM2 { get; set; }
        public Nullable<decimal> RBAM3 { get; set; }
        public Nullable<int> RBGRP { get; set; }
        public string RBFLA { get; set; }
        public string RBFLB { get; set; }
        public string RBPIK { get; set; }
        public string FlagSet { get; set; }
        public string RSZXA { get; set; }
        public string RBPRO { get; set; }
        public Nullable<int> RBPNT { get; set; }
    }
}
