//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIQA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSIQA()
        {
            this.RSIQBBs = new HashSet<RSIQBB>();
        }
    
        public string RAREN { get; set; }
        public string RACNS { get; set; }
        public string RACN2 { get; set; }
        public string RAOEN { get; set; }
        public string RANUM { get; set; }
        public string RASHP { get; set; }
        public string RACLS { get; set; }
        public string RACTS { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public Nullable<System.DateTime> RADAV { get; set; }
        public string RAINV { get; set; }
        public Nullable<int> RAINQ { get; set; }
        public string RARMA { get; set; }
        public string RAMEN { get; set; }
        public string RASAL { get; set; }
        public string RAEDT { get; set; }
        public string RACSR { get; set; }
        public string RARER { get; set; }
        public string RACAR { get; set; }
        public string RACS1 { get; set; }
        public string RACS2 { get; set; }
        public Nullable<decimal> RATAX { get; set; }
        public Nullable<decimal> RATOL { get; set; }
        public Nullable<double> RAQTY { get; set; }
        public string RAVIP { get; set; }
        public string RAMN3 { get; set; }
        public string RAADR { get; set; }
        public Nullable<double> RAAMR { get; set; }
        public string RATEL { get; set; }
        public Nullable<System.DateTime> RASDT { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRMOD { get; set; }
        public string TRUSR { get; set; }
        public string RAINN { get; set; }
        public string RAREV { get; set; }
        public string RAREX { get; set; }
        public string RABIR { get; set; }
        public string RACLA { get; set; }
        public string RASKP { get; set; }
        public Nullable<int> RAPNT { get; set; }
        public string RACER { get; set; }
        public Nullable<System.DateTime> RAXDT { get; set; }
        public string RARBN { get; set; }
        public string RABTM { get; set; }
        public string RAJoinCard { get; set; }
        public string OriginalRACAR { get; set; }
    
        public virtual BCU BCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSIQBB> RSIQBBs { get; set; }
    }
}
