//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSIYB
    {
        public string RBNUM { get; set; }
        public System.DateTime RBDAY { get; set; }
        public string RBITM { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBCLZ { get; set; }
        public Nullable<int> RBQTY { get; set; }
        public Nullable<int> RBQTY01 { get; set; }
        public Nullable<int> RBQTY02 { get; set; }
        public Nullable<int> RBQTY03 { get; set; }
        public Nullable<int> RBQTY04 { get; set; }
        public Nullable<int> RBQTY05 { get; set; }
        public Nullable<int> RBQTY06 { get; set; }
        public Nullable<int> RBQTY07 { get; set; }
        public Nullable<int> RBQTY08 { get; set; }
        public Nullable<int> RBQTY09 { get; set; }
        public Nullable<int> RBQTY10 { get; set; }
        public Nullable<int> RBQTY11 { get; set; }
        public Nullable<int> RBQTY12 { get; set; }
        public Nullable<int> RBQTY13 { get; set; }
        public Nullable<int> RBQTY14 { get; set; }
        public Nullable<int> RBQTY15 { get; set; }
        public Nullable<int> RBQTY16 { get; set; }
        public Nullable<int> RBQTY17 { get; set; }
        public Nullable<int> RBQTY18 { get; set; }
        public Nullable<int> RBQTY19 { get; set; }
        public Nullable<int> RBQTY20 { get; set; }
        public Nullable<int> RBQTY21 { get; set; }
        public Nullable<int> RBQTY22 { get; set; }
        public Nullable<int> RBQTY23 { get; set; }
        public Nullable<int> RBQTY24 { get; set; }
        public Nullable<int> RBQTY25 { get; set; }
        public Nullable<int> RBQTY26 { get; set; }
        public Nullable<int> RBQTY27 { get; set; }
        public Nullable<int> RBQTY28 { get; set; }
        public Nullable<int> RBQTY29 { get; set; }
        public Nullable<int> RBQTY30 { get; set; }
    
        public virtual BSTL BSTL { get; set; }
        public virtual RSIYA RSIYA { get; set; }
    }
}
