//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSNNC
    {
        public string RCREN { get; set; }
        public string RCITM { get; set; }
        public string RCIEC { get; set; }
        public string RCNUM { get; set; }
        public string RCNCR { get; set; }
        public string RCCLR { get; set; }
        public string RCCLZ { get; set; }
        public Nullable<int> RCQTY { get; set; }
        public Nullable<double> RCQTY01 { get; set; }
        public Nullable<double> RCQTY02 { get; set; }
        public Nullable<double> RCQTY03 { get; set; }
        public Nullable<double> RCQTY04 { get; set; }
        public Nullable<double> RCQTY05 { get; set; }
        public Nullable<double> RCQTY06 { get; set; }
        public Nullable<double> RCQTY07 { get; set; }
        public Nullable<double> RCQTY08 { get; set; }
        public Nullable<double> RCQTY09 { get; set; }
        public Nullable<double> RCQTY10 { get; set; }
        public Nullable<double> RCQTY11 { get; set; }
        public Nullable<double> RCQTY12 { get; set; }
        public Nullable<double> RCQTY13 { get; set; }
        public Nullable<double> RCQTY14 { get; set; }
        public Nullable<double> RCQTY15 { get; set; }
        public Nullable<double> RCQTY16 { get; set; }
        public Nullable<double> RCQTY17 { get; set; }
        public Nullable<double> RCQTY18 { get; set; }
        public Nullable<double> RCQTY19 { get; set; }
        public Nullable<double> RCQTY20 { get; set; }
        public Nullable<double> RCQTY21 { get; set; }
        public Nullable<double> RCQTY22 { get; set; }
        public Nullable<double> RCQTY23 { get; set; }
        public Nullable<double> RCQTY24 { get; set; }
        public Nullable<double> RCQTY25 { get; set; }
        public Nullable<double> RCQTY26 { get; set; }
        public Nullable<double> RCQTY27 { get; set; }
        public Nullable<double> RCQTY28 { get; set; }
        public Nullable<double> RCQTY29 { get; set; }
        public Nullable<double> RCQTY30 { get; set; }
    
        public virtual RSNNB RSNNB { get; set; }
    }
}
