//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSNNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSNNA()
        {
            this.RSNNBs = new HashSet<RSNNB>();
        }
    
        public string RAREN { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public string RANUM { get; set; }
        public Nullable<System.DateTime> RADEL { get; set; }
        public string RAMEN { get; set; }
        public string TRUSR { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string RARER { get; set; }
        public string RARMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSNNB> RSNNBs { get; set; }
    }
}
