//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSPB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBNNO { get; set; }
        public string RBSEQ { get; set; }
        public string RBNUM { get; set; }
        public string RBPNR { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBCLZ { get; set; }
        public Nullable<decimal> RBUPC { get; set; }
        public int RBDCX { get; set; }
        public decimal RBAMT { get; set; }
        public string RBRMK { get; set; }
        public string RBSUM { get; set; }
        public string RBCSR { get; set; }
        public string RBRER { get; set; }
        public string RBIEM { get; set; }
        public string RBIEC { get; set; }
        public string RBREQ { get; set; }
        public string RBITQ { get; set; }
        public string RBREV { get; set; }
        public Nullable<System.DateTime> RBDEL { get; set; }
        public decimal RBDPC { get; set; }
        public double RBQTY { get; set; }
        public Nullable<double> RBQTY01 { get; set; }
        public Nullable<double> RBQTY02 { get; set; }
        public Nullable<double> RBQTY03 { get; set; }
        public Nullable<double> RBQTY04 { get; set; }
        public Nullable<double> RBQTY05 { get; set; }
        public Nullable<double> RBQTY06 { get; set; }
        public Nullable<double> RBQTY07 { get; set; }
        public Nullable<double> RBQTY08 { get; set; }
        public Nullable<double> RBQTY09 { get; set; }
        public Nullable<double> RBQTY10 { get; set; }
        public Nullable<double> RBQTY11 { get; set; }
        public Nullable<double> RBQTY12 { get; set; }
        public Nullable<double> RBQTY13 { get; set; }
        public Nullable<double> RBQTY14 { get; set; }
        public Nullable<double> RBQTY15 { get; set; }
        public Nullable<double> RBQTY16 { get; set; }
        public Nullable<double> RBQTY17 { get; set; }
        public Nullable<double> RBQTY18 { get; set; }
        public Nullable<double> RBQTY19 { get; set; }
        public Nullable<double> RBQTY20 { get; set; }
        public string RBFLG1 { get; set; }
        public string RBFLG2 { get; set; }
        public Nullable<double> RBQTY21 { get; set; }
        public Nullable<double> RBQTY22 { get; set; }
        public Nullable<double> RBQTY23 { get; set; }
        public Nullable<double> RBQTY24 { get; set; }
        public Nullable<double> RBQTY25 { get; set; }
        public Nullable<double> RBQTY26 { get; set; }
        public Nullable<double> RBQTY27 { get; set; }
        public Nullable<double> RBQTY28 { get; set; }
        public Nullable<double> RBQTY29 { get; set; }
        public Nullable<double> RBQTY30 { get; set; }
    
        public virtual BSHB BSHB { get; set; }
        public virtual RSPA RSPA { get; set; }
    }
}
