//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSPPB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSPPB()
        {
            this.RSPPCs = new HashSet<RSPPC>();
        }
    
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBPNR { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBCLZ { get; set; }
        public Nullable<double> RBUPC { get; set; }
        public Nullable<decimal> RBDCX { get; set; }
        public Nullable<decimal> RBAMT { get; set; }
        public string RBRMK { get; set; }
        public string RBREQ { get; set; }
        public string RBITQ { get; set; }
        public string RBREV { get; set; }
        public Nullable<System.DateTime> RBDEL { get; set; }
        public Nullable<double> RBQTY { get; set; }
        public Nullable<double> RBMRK { get; set; }
        public Nullable<double> RBUPS { get; set; }
        public Nullable<double> RBRAT { get; set; }
        public string RBSEA { get; set; }
        public string RBYER { get; set; }
        public string RBSEX { get; set; }
        public string RBLAB { get; set; }
        public string RBOCR { get; set; }
        public string RBNAM { get; set; }
        public string RBGLA { get; set; }
        public Nullable<decimal> RBFOR { get; set; }
        public string RBCLA { get; set; }
        public string RBPNO { get; set; }
        public Nullable<double> RBQTY01 { get; set; }
        public Nullable<double> RBQTY02 { get; set; }
        public Nullable<double> RBQTY03 { get; set; }
        public Nullable<double> RBQTY04 { get; set; }
        public Nullable<double> RBQTY05 { get; set; }
        public Nullable<double> RBQTY06 { get; set; }
        public Nullable<double> RBQTY07 { get; set; }
        public Nullable<double> RBQTY08 { get; set; }
        public Nullable<double> RBQTY09 { get; set; }
        public Nullable<double> RBQTY10 { get; set; }
        public Nullable<double> RBQTY11 { get; set; }
        public Nullable<double> RBQTY12 { get; set; }
        public Nullable<double> RBQTY13 { get; set; }
        public Nullable<double> RBQTY14 { get; set; }
        public Nullable<double> RBQTY15 { get; set; }
        public Nullable<double> RBQTY16 { get; set; }
        public Nullable<double> RBQTY17 { get; set; }
        public Nullable<double> RBQTY18 { get; set; }
        public Nullable<double> RBQTY19 { get; set; }
        public Nullable<double> RBQTY20 { get; set; }
        public Nullable<double> RBOQY { get; set; }
        public Nullable<double> RBOQY01 { get; set; }
        public Nullable<double> RBOQY02 { get; set; }
        public Nullable<double> RBOQY03 { get; set; }
        public Nullable<double> RBOQY04 { get; set; }
        public Nullable<double> RBOQY05 { get; set; }
        public Nullable<double> RBOQY06 { get; set; }
        public Nullable<double> RBOQY07 { get; set; }
        public Nullable<double> RBOQY08 { get; set; }
        public Nullable<double> RBOQY09 { get; set; }
        public Nullable<double> RBOQY10 { get; set; }
        public Nullable<double> RBOQY11 { get; set; }
        public Nullable<double> RBOQY12 { get; set; }
        public Nullable<double> RBOQY13 { get; set; }
        public Nullable<double> RBOQY14 { get; set; }
        public Nullable<double> RBOQY15 { get; set; }
        public Nullable<double> RBOQY16 { get; set; }
        public Nullable<double> RBOQY17 { get; set; }
        public Nullable<double> RBOQY18 { get; set; }
        public Nullable<double> RBOQY19 { get; set; }
        public Nullable<double> RBOQY20 { get; set; }
        public string RBRER { get; set; }
        public string RBIEM { get; set; }
        public Nullable<double> RBQTY21 { get; set; }
        public Nullable<double> RBQTY22 { get; set; }
        public Nullable<double> RBQTY23 { get; set; }
        public Nullable<double> RBQTY24 { get; set; }
        public Nullable<double> RBQTY25 { get; set; }
        public Nullable<double> RBQTY26 { get; set; }
        public Nullable<double> RBQTY27 { get; set; }
        public Nullable<double> RBQTY28 { get; set; }
        public Nullable<double> RBQTY29 { get; set; }
        public Nullable<double> RBQTY30 { get; set; }
        public Nullable<double> RBOQY21 { get; set; }
        public Nullable<double> RBOQY22 { get; set; }
        public Nullable<double> RBOQY23 { get; set; }
        public Nullable<double> RBOQY24 { get; set; }
        public Nullable<double> RBOQY25 { get; set; }
        public Nullable<double> RBOQY26 { get; set; }
        public Nullable<double> RBOQY27 { get; set; }
        public Nullable<double> RBOQY28 { get; set; }
        public Nullable<double> RBOQY29 { get; set; }
        public Nullable<double> RBOQY30 { get; set; }
    
        public virtual RSPPA RSPPA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSPPC> RSPPCs { get; set; }
    }
}
