//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSPPC
    {
        public string RCREN { get; set; }
        public string RCITM { get; set; }
        public string RCIEC { get; set; }
        public string RCNUM { get; set; }
        public string RCNCR { get; set; }
        public string RCCLR { get; set; }
        public string RCCLZ { get; set; }
        public Nullable<double> RCQTY { get; set; }
        public Nullable<double> RCQTY01 { get; set; }
        public Nullable<double> RCQTY02 { get; set; }
        public Nullable<double> RCQTY03 { get; set; }
        public Nullable<double> RCQTY04 { get; set; }
        public Nullable<double> RCQTY05 { get; set; }
        public Nullable<double> RCQTY06 { get; set; }
        public Nullable<double> RCQTY07 { get; set; }
        public Nullable<double> RCQTY08 { get; set; }
        public Nullable<double> RCQTY09 { get; set; }
        public Nullable<double> RCQTY10 { get; set; }
        public Nullable<double> RCQTY11 { get; set; }
        public Nullable<double> RCQTY12 { get; set; }
        public Nullable<double> RCQTY13 { get; set; }
        public Nullable<double> RCQTY14 { get; set; }
        public Nullable<double> RCQTY15 { get; set; }
        public Nullable<double> RCQTY16 { get; set; }
        public Nullable<double> RCQTY17 { get; set; }
        public Nullable<double> RCQTY18 { get; set; }
        public Nullable<double> RCQTY19 { get; set; }
        public Nullable<double> RCQTY20 { get; set; }
        public Nullable<double> RCOQY { get; set; }
        public Nullable<double> RCOQY01 { get; set; }
        public Nullable<double> RCOQY02 { get; set; }
        public Nullable<double> RCOQY03 { get; set; }
        public Nullable<double> RCOQY04 { get; set; }
        public Nullable<double> RCOQY05 { get; set; }
        public Nullable<double> RCOQY06 { get; set; }
        public Nullable<double> RCOQY07 { get; set; }
        public Nullable<double> RCOQY08 { get; set; }
        public Nullable<double> RCOQY09 { get; set; }
        public Nullable<double> RCOQY10 { get; set; }
        public Nullable<double> RCOQY11 { get; set; }
        public Nullable<double> RCOQY12 { get; set; }
        public Nullable<double> RCOQY13 { get; set; }
        public Nullable<double> RCOQY14 { get; set; }
        public Nullable<double> RCOQY15 { get; set; }
        public Nullable<double> RCOQY16 { get; set; }
        public Nullable<double> RCOQY17 { get; set; }
        public Nullable<double> RCOQY18 { get; set; }
        public Nullable<double> RCOQY19 { get; set; }
        public Nullable<double> RCOQY20 { get; set; }
        public Nullable<double> RCQTY21 { get; set; }
        public Nullable<double> RCQTY22 { get; set; }
        public Nullable<double> RCQTY23 { get; set; }
        public Nullable<double> RCQTY24 { get; set; }
        public Nullable<double> RCQTY25 { get; set; }
        public Nullable<double> RCQTY26 { get; set; }
        public Nullable<double> RCQTY27 { get; set; }
        public Nullable<double> RCQTY28 { get; set; }
        public Nullable<double> RCQTY29 { get; set; }
        public Nullable<double> RCQTY30 { get; set; }
        public Nullable<double> RCOQY21 { get; set; }
        public Nullable<double> RCOQY22 { get; set; }
        public Nullable<double> RCOQY23 { get; set; }
        public Nullable<double> RCOQY24 { get; set; }
        public Nullable<double> RCOQY25 { get; set; }
        public Nullable<double> RCOQY26 { get; set; }
        public Nullable<double> RCOQY27 { get; set; }
        public Nullable<double> RCOQY28 { get; set; }
        public Nullable<double> RCOQY29 { get; set; }
        public Nullable<double> RCOQY30 { get; set; }
    
        public virtual RSPPB RSPPB { get; set; }
    }
}
