//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSRA()
        {
            this.RSRBs = new HashSet<RSRB>();
        }
    
        public string RAREN { get; set; }
        public string RANUM { get; set; }
        public string RASHP { get; set; }
        public string RACNS { get; set; }
        public System.DateTime RADAT { get; set; }
        public System.DateTime RADAY { get; set; }
        public string RAMEN { get; set; }
        public string RAMNY { get; set; }
        public double RARAT { get; set; }
        public string RACS1 { get; set; }
        public string RACS2 { get; set; }
        public double RATAX { get; set; }
        public Nullable<System.DateTime> RADEL { get; set; }
        public Nullable<double> RATOL { get; set; }
        public Nullable<double> RAQTY { get; set; }
        public string RARM1 { get; set; }
        public string RARM2 { get; set; }
        public string RARMK { get; set; }
        public string RADEV { get; set; }
        public string RADNM { get; set; }
        public string RAFLG { get; set; }
        public string RASAL { get; set; }
        public string RACAR { get; set; }
        public string RAKIN { get; set; }
        public string RACMN { get; set; }
        public string RARMK02 { get; set; }
        public string RARMK03 { get; set; }
        public string RARMK04 { get; set; }
        public string RARMK05 { get; set; }
    
        public virtual BCU BCU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSRB> RSRBs { get; set; }
    }
}
