//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSRB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public Nullable<System.DateTime> RBDEL { get; set; }
        public string RBCLZ { get; set; }
        public double RBUPC { get; set; }
        public Nullable<double> RBDPC { get; set; }
        public double RBDCX { get; set; }
        public double RBAMT { get; set; }
        public string RBRMK { get; set; }
        public double RBQTY { get; set; }
        public Nullable<double> RBQTY01 { get; set; }
        public Nullable<double> RBQTY02 { get; set; }
        public Nullable<double> RBQTY03 { get; set; }
        public Nullable<double> RBQTY04 { get; set; }
        public Nullable<double> RBQTY05 { get; set; }
        public Nullable<double> RBQTY06 { get; set; }
        public Nullable<double> RBQTY07 { get; set; }
        public Nullable<double> RBQTY08 { get; set; }
        public Nullable<double> RBQTY09 { get; set; }
        public Nullable<double> RBQTY10 { get; set; }
        public Nullable<double> RBQTY11 { get; set; }
        public Nullable<double> RBQTY12 { get; set; }
        public Nullable<double> RBQTY13 { get; set; }
        public Nullable<double> RBQTY14 { get; set; }
        public Nullable<double> RBQTY15 { get; set; }
        public Nullable<double> RBQTY16 { get; set; }
        public Nullable<double> RBQTY17 { get; set; }
        public Nullable<double> RBQTY18 { get; set; }
        public Nullable<double> RBQTY19 { get; set; }
        public Nullable<double> RBQTY20 { get; set; }
        public Nullable<double> RBAQY { get; set; }
        public Nullable<double> RBAQY01 { get; set; }
        public Nullable<double> RBAQY02 { get; set; }
        public Nullable<double> RBAQY03 { get; set; }
        public Nullable<double> RBAQY04 { get; set; }
        public Nullable<double> RBAQY05 { get; set; }
        public Nullable<double> RBAQY06 { get; set; }
        public Nullable<double> RBAQY07 { get; set; }
        public Nullable<double> RBAQY08 { get; set; }
        public Nullable<double> RBAQY09 { get; set; }
        public Nullable<double> RBAQY10 { get; set; }
        public Nullable<double> RBAQY11 { get; set; }
        public Nullable<double> RBAQY12 { get; set; }
        public Nullable<double> RBAQY13 { get; set; }
        public Nullable<double> RBAQY14 { get; set; }
        public Nullable<double> RBAQY15 { get; set; }
        public Nullable<double> RBAQY16 { get; set; }
        public Nullable<double> RBAQY17 { get; set; }
        public Nullable<double> RBAQY18 { get; set; }
        public Nullable<double> RBAQY19 { get; set; }
        public Nullable<double> RBAQY20 { get; set; }
        public Nullable<double> RBQTY21 { get; set; }
        public Nullable<double> RBQTY22 { get; set; }
        public Nullable<double> RBQTY23 { get; set; }
        public Nullable<double> RBQTY24 { get; set; }
        public Nullable<double> RBQTY25 { get; set; }
        public Nullable<double> RBQTY26 { get; set; }
        public Nullable<double> RBQTY27 { get; set; }
        public Nullable<double> RBQTY28 { get; set; }
        public Nullable<double> RBQTY29 { get; set; }
        public Nullable<double> RBQTY30 { get; set; }
        public Nullable<double> RBAQY21 { get; set; }
        public Nullable<double> RBAQY22 { get; set; }
        public Nullable<double> RBAQY23 { get; set; }
        public Nullable<double> RBAQY24 { get; set; }
        public Nullable<double> RBAQY25 { get; set; }
        public Nullable<double> RBAQY26 { get; set; }
        public Nullable<double> RBAQY27 { get; set; }
        public Nullable<double> RBAQY28 { get; set; }
        public Nullable<double> RBAQY29 { get; set; }
        public Nullable<double> RBAQY30 { get; set; }
        public string SENCR { get; set; }
        public Nullable<double> RBCQY { get; set; }
        public Nullable<double> RBCQY01 { get; set; }
        public Nullable<double> RBCQY02 { get; set; }
        public Nullable<double> RBCQY03 { get; set; }
        public Nullable<double> RBCQY04 { get; set; }
        public Nullable<double> RBCQY05 { get; set; }
        public Nullable<double> RBCQY06 { get; set; }
        public Nullable<double> RBCQY07 { get; set; }
        public Nullable<double> RBCQY08 { get; set; }
        public Nullable<double> RBCQY09 { get; set; }
        public Nullable<double> RBCQY10 { get; set; }
        public Nullable<double> RBCQY11 { get; set; }
        public Nullable<double> RBCQY12 { get; set; }
        public Nullable<double> RBCQY13 { get; set; }
        public Nullable<double> RBCQY14 { get; set; }
        public Nullable<double> RBCQY15 { get; set; }
        public Nullable<double> RBCQY16 { get; set; }
        public Nullable<double> RBCQY17 { get; set; }
        public Nullable<double> RBCQY18 { get; set; }
        public Nullable<double> RBCQY19 { get; set; }
        public Nullable<double> RBCQY20 { get; set; }
        public Nullable<double> RBCQY21 { get; set; }
        public Nullable<double> RBCQY22 { get; set; }
        public Nullable<double> RBCQY23 { get; set; }
        public Nullable<double> RBCQY24 { get; set; }
        public Nullable<double> RBCQY25 { get; set; }
        public Nullable<double> RBCQY26 { get; set; }
        public Nullable<double> RBCQY27 { get; set; }
        public Nullable<double> RBCQY28 { get; set; }
        public Nullable<double> RBCQY29 { get; set; }
        public Nullable<double> RBCQY30 { get; set; }
    
        public virtual RSRA RSRA { get; set; }
    }
}
