//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSTP
    {
        public string BSNCR { get; set; }
        public string BSCLR { get; set; }
        public string BSITZ { get; set; }
        public string BSYMM { get; set; }
        public string BSCNS { get; set; }
        public string BSFLG { get; set; }
        public Nullable<int> BSQTA { get; set; }
        public Nullable<decimal> BSUPA { get; set; }
        public Nullable<int> BSQT1 { get; set; }
        public Nullable<decimal> BSUP1 { get; set; }
        public Nullable<int> BSQT2 { get; set; }
        public Nullable<decimal> BSUP2 { get; set; }
        public Nullable<double> BSQ1X { get; set; }
        public Nullable<double> BSQTC { get; set; }
        public Nullable<int> BSQT3 { get; set; }
        public Nullable<decimal> BSUP3 { get; set; }
        public Nullable<int> BSQT4 { get; set; }
        public Nullable<double> BSQTD { get; set; }
        public Nullable<int> BSQT5 { get; set; }
        public Nullable<int> BSQT6 { get; set; }
        public Nullable<int> BSQ55 { get; set; }
        public Nullable<int> BSQ56 { get; set; }
        public Nullable<int> BSQT7 { get; set; }
        public Nullable<int> BSQT8 { get; set; }
        public Nullable<double> BSQTF { get; set; }
        public Nullable<double> BSQTG { get; set; }
        public Nullable<int> BSQTN { get; set; }
        public Nullable<double> BSQWA { get; set; }
        public Nullable<double> BSQWW { get; set; }
        public Nullable<double> BSQWX { get; set; }
        public Nullable<double> BSQWY { get; set; }
        public Nullable<double> BSUWY { get; set; }
        public Nullable<double> BSQWN { get; set; }
        public Nullable<double> BSQCA { get; set; }
        public Nullable<double> BSQCC { get; set; }
        public Nullable<double> BSQCH { get; set; }
        public Nullable<double> BSQCJ { get; set; }
        public Nullable<double> BSQCI { get; set; }
        public Nullable<double> BSQCN { get; set; }
        public Nullable<double> BSYDQ { get; set; }
        public Nullable<double> BSYDP { get; set; }
        public string BSSIZ { get; set; }
    
        public virtual BCU BCU { get; set; }
        public virtual RSTN RSTN { get; set; }
    }
}
