//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSVAsumA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSVAsumA()
        {
            this.RSVAsumBs = new HashSet<RSVAsumB>();
            this.RSVAsumCs = new HashSet<RSVAsumC>();
        }
    
        public string RAREN { get; set; }
        public System.DateTime RADAY { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public System.DateTime RAXDT { get; set; }
        public string RAMEN { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
        public string RATYP { get; set; }
        public string RAFLG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSVAsumB> RSVAsumBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RSVAsumC> RSVAsumCs { get; set; }
    }
}
