//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSWC
    {
        public string RCREN { get; set; }
        public string RCITM { get; set; }
        public string RCIEC { get; set; }
        public string RCCNS { get; set; }
        public string RCNCR { get; set; }
        public string RCCLR { get; set; }
        public string RCCLZ { get; set; }
        public Nullable<double> RCQTY { get; set; }
        public Nullable<double> RCQTY01 { get; set; }
        public Nullable<double> RCQTY02 { get; set; }
        public Nullable<double> RCQTY03 { get; set; }
        public Nullable<double> RCQTY04 { get; set; }
        public Nullable<double> RCQTY05 { get; set; }
        public Nullable<double> RCQTY06 { get; set; }
        public Nullable<double> RCQTY07 { get; set; }
        public Nullable<double> RCQTY08 { get; set; }
        public Nullable<double> RCQTY09 { get; set; }
        public Nullable<double> RCQTY10 { get; set; }
        public Nullable<double> RCQTY11 { get; set; }
        public Nullable<double> RCQTY12 { get; set; }
        public Nullable<double> RCQTY13 { get; set; }
        public Nullable<double> RCQTY14 { get; set; }
        public Nullable<double> RCQTY15 { get; set; }
        public Nullable<double> RCQTY16 { get; set; }
        public Nullable<double> RCQTY17 { get; set; }
        public Nullable<double> RCQTY18 { get; set; }
        public Nullable<double> RCQTY19 { get; set; }
        public Nullable<double> RCQTY20 { get; set; }
        public Nullable<double> RCPQY { get; set; }
        public Nullable<double> RCPQY01 { get; set; }
        public Nullable<double> RCPQY02 { get; set; }
        public Nullable<double> RCPQY03 { get; set; }
        public Nullable<double> RCPQY04 { get; set; }
        public Nullable<double> RCPQY05 { get; set; }
        public Nullable<double> RCPQY06 { get; set; }
        public Nullable<double> RCPQY07 { get; set; }
        public Nullable<double> RCPQY08 { get; set; }
        public Nullable<double> RCPQY09 { get; set; }
        public Nullable<double> RCPQY10 { get; set; }
        public Nullable<double> RCPQY11 { get; set; }
        public Nullable<double> RCPQY12 { get; set; }
        public Nullable<double> RCPQY13 { get; set; }
        public Nullable<double> RCPQY14 { get; set; }
        public Nullable<double> RCPQY15 { get; set; }
        public Nullable<double> RCPQY16 { get; set; }
        public Nullable<double> RCPQY17 { get; set; }
        public Nullable<double> RCPQY18 { get; set; }
        public Nullable<double> RCPQY19 { get; set; }
        public Nullable<double> RCPQY20 { get; set; }
        public Nullable<double> RCQTY21 { get; set; }
        public Nullable<double> RCQTY22 { get; set; }
        public Nullable<double> RCQTY23 { get; set; }
        public Nullable<double> RCQTY24 { get; set; }
        public Nullable<double> RCQTY25 { get; set; }
        public Nullable<double> RCQTY26 { get; set; }
        public Nullable<double> RCQTY27 { get; set; }
        public Nullable<double> RCQTY28 { get; set; }
        public Nullable<double> RCQTY29 { get; set; }
        public Nullable<double> RCQTY30 { get; set; }
        public Nullable<double> RCPQY21 { get; set; }
        public Nullable<double> RCPQY22 { get; set; }
        public Nullable<double> RCPQY23 { get; set; }
        public Nullable<double> RCPQY24 { get; set; }
        public Nullable<double> RCPQY25 { get; set; }
        public Nullable<double> RCPQY26 { get; set; }
        public Nullable<double> RCPQY27 { get; set; }
        public Nullable<double> RCPQY28 { get; set; }
        public Nullable<double> RCPQY29 { get; set; }
        public Nullable<double> RCPQY30 { get; set; }
    
        public virtual RSWB RSWB { get; set; }
    }
}
