//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSZA
    {
        public string RAREN { get; set; }
        public string RAITM { get; set; }
        public string RACLS { get; set; }
        public Nullable<decimal> RAQTY { get; set; }
        public Nullable<double> RADCX { get; set; }
        public Nullable<double> RAUP2 { get; set; }
        public System.DateTime RADTS { get; set; }
        public System.DateTime RADTE { get; set; }
        public string RARMK { get; set; }
        public Nullable<int> RACHK { get; set; }
        public string RANOT { get; set; }
        public string RAKND { get; set; }
        public string JoinType { get; set; }
        public string RAMEN { get; set; }
        public Nullable<System.DateTime> RADAT { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> ExpireDay { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string FlagSet { get; set; }
        public string RAGLA { get; set; }
        public string RALAB { get; set; }
        public string RACLA { get; set; }
        public string RAUSE { get; set; }
        public Nullable<decimal> RARED { get; set; }
        public Nullable<decimal> RAGRN { get; set; }
        public Nullable<decimal> RAYLW { get; set; }
        public string RAUEF { get; set; }
        public string RAJFC { get; set; }
        public Nullable<int> Stair1 { get; set; }
        public Nullable<int> Stair2 { get; set; }
        public Nullable<int> Stair3 { get; set; }
        public Nullable<int> Stair4 { get; set; }
        public Nullable<int> StairNo { get; set; }
        public Nullable<int> RAAMT { get; set; }
    }
}
