//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSZB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBITX { get; set; }
        public string RBCOS { get; set; }
        public string RBCTS { get; set; }
        public string RBRGT { get; set; }
        public string RBPTN { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBITZ { get; set; }
        public string RBSIZ { get; set; }
        public Nullable<decimal> RBQTY { get; set; }
        public Nullable<decimal> RBDCX { get; set; }
        public Nullable<decimal> RBUPC { get; set; }
        public Nullable<decimal> RBUP2 { get; set; }
        public Nullable<decimal> RBAMT { get; set; }
        public Nullable<decimal> RBUP3 { get; set; }
        public string Kind { get; set; }
    }
}
