//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSZBBB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBCNS { get; set; }
        public System.DateTime RBDTS { get; set; }
        public Nullable<System.DateTime> RBDTE { get; set; }
    
        public virtual BCU BCU { get; set; }
        public virtual RSZBA RSZBA { get; set; }
    }
}
