//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RVSB
    {
        public string RBREN { get; set; }
        public string RBITM { get; set; }
        public string RBONU { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public string RBSIZ { get; set; }
        public Nullable<double> RBQTY { get; set; }
        public Nullable<double> RBUP1 { get; set; }
        public Nullable<double> RBUPC { get; set; }
        public Nullable<double> RBAM1 { get; set; }
        public Nullable<double> RBAMT { get; set; }
    
        public virtual RVSA RVSA { get; set; }
    }
}
