//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class RVT
    {
        public string RAYMM { get; set; }
        public string RAITM { get; set; }
        public string RACS1 { get; set; }
        public string RACNX { get; set; }
        public string RAIN1 { get; set; }
        public string RAIN2 { get; set; }
        public string RAIN3 { get; set; }
        public string RAMEN { get; set; }
        public Nullable<System.DateTime> RADAY { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string SalesType { get; set; }
        public string RegionNo { get; set; }
        public string PosMachineNo { get; set; }
        public string RANUM { get; set; }
        public string InvoiceTrackBan { get; set; }
        public Nullable<System.DateTime> BranchTrackTranDateTime { get; set; }
        public Nullable<System.DateTime> BlankTranDateTime { get; set; }
        public string IsEInvoice { get; set; }
        public string InvoiceBeginNo { get; set; }
        public string InvoiceEndNo { get; set; }
        public Nullable<int> InvoiceBooklet { get; set; }
        public string RBRER { get; set; }
    }
}
