//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLBARCODEB
    {
        public string SENUM { get; set; }
        public string SENCR { get; set; }
        public string SBITM { get; set; }
        public string SBNCR { get; set; }
        public string SBNAM { get; set; }
        public string SBCLR { get; set; }
        public string SBSIZ { get; set; }
        public string SBTRE { get; set; }
        public string SBKID { get; set; }
        public string SBCNS { get; set; }
        public System.DateTime SBsDATE { get; set; }
        public Nullable<System.DateTime> SBeDATE { get; set; }
        public string SBRSZA { get; set; }
    
        public virtual SELLBARCODEA SELLBARCODEA { get; set; }
    }
}
