//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftNotEnough
    {
        public string RBYMM { get; set; }
        public string RBENO { get; set; }
        public string RBCNS { get; set; }
        public Nullable<double> ShouldHR { get; set; }
        public Nullable<double> ShiftHR { get; set; }
        public Nullable<double> DeductPerHR { get; set; }
        public Nullable<decimal> ShiftDeduction { get; set; }
        public Nullable<double> ApproveOverHR { get; set; }
        public Nullable<decimal> TReal { get; set; }
    }
}
