//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftTime
    {
        public string BSCNS { get; set; }
        public string ShiftKind { get; set; }
        public string StartHur { get; set; }
        public string StartMin { get; set; }
        public string EndHur { get; set; }
        public string EndMin { get; set; }
        public int WeekDay { get; set; }
        public Nullable<decimal> ExceptionTime { get; set; }
    }
}
