//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinvoice
    {
        public string RANUM { get; set; }
        public string RANUMName { get; set; }
        public string RAYER { get; set; }
        public Nullable<decimal> SumPayAMT { get; set; }
        public Nullable<decimal> SumRinvoiceAMT { get; set; }
        public string RARMA { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
        public string TRUSR { get; set; }
    }
}
