//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStoreValid
    {
        public string TSYMM { get; set; }
        public System.DateTime TSDAY { get; set; }
        public string TSCNS { get; set; }
        public string TSTYPE { get; set; }
        public Nullable<int> TSCOUNT { get; set; }
        public Nullable<int> TSTOL { get; set; }
    }
}
