//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempWellan
    {
        public string BSNCR { get; set; }
        public string BSCLR { get; set; }
        public string BSSIZ { get; set; }
        public string BSCNS { get; set; }
        public Nullable<int> BSQTY { get; set; }
        public string BSONU { get; set; }
        public string BSITZ { get; set; }
        public string BSNUM { get; set; }
    }
}
