//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPSALESBONU
    {
        public string RBYMM { get; set; }
        public string RBREN { get; set; }
        public Nullable<System.DateTime> RBDAY { get; set; }
        public string RBCNS { get; set; }
        public string RBBCS { get; set; }
        public string RBITM { get; set; }
        public string RBRER { get; set; }
        public string RBITE { get; set; }
        public string RBNCR { get; set; }
        public string RBCLR { get; set; }
        public Nullable<decimal> RBAM1 { get; set; }
        public Nullable<decimal> RBEED { get; set; }
        public Nullable<decimal> RBDCX { get; set; }
        public Nullable<decimal> RBSALRAT { get; set; }
        public Nullable<decimal> RBWTVAL { get; set; }
        public Nullable<decimal> RBVAL { get; set; }
        public string TRUSR { get; set; }
        public Nullable<System.DateTime> TRDAT { get; set; }
    }
}
