//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempBPSNValid
    {
        public string TBYMM { get; set; }
        public string TBENO { get; set; }
        public string TBTIT { get; set; }
        public string TBCNU { get; set; }
        public Nullable<System.DateTime> TBFDY { get; set; }
        public Nullable<System.DateTime> TBEDY { get; set; }
        public Nullable<System.DateTime> TBTBD { get; set; }
        public Nullable<System.DateTime> TBTED { get; set; }
        public Nullable<int> TBVAD { get; set; }
        public int TBKEY { get; set; }
    }
}
