//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeClock
    {
        public string BSYMD { get; set; }
        public string BSTYP { get; set; }
        public string BSCNS { get; set; }
        public string UserLogName { get; set; }
        public Nullable<System.DateTime> BSDAY { get; set; }
        public string BSRMK { get; set; }
        public string BSMOD { get; set; }
        public string IP { get; set; }
        public string BSClass { get; set; }
    }
}
