//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class uAddress
    {
        public int uAddressKey { get; set; }
        public string BACO1 { get; set; }
        public string BACO2 { get; set; }
        public string BACTY { get; set; }
        public string BAARE { get; set; }
        public string BASTR { get; set; }
        public string RegionNo { get; set; }
    }
}
