//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserLogID { get; set; }
        public string FunctionID { get; set; }
        public string EventCatalog { get; set; }
        public string Message { get; set; }
        public string UserID { get; set; }
        public string OrgNo { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> EventTime { get; set; }
        public string URL { get; set; }
        public string RemoteIP { get; set; }
        public string extField1 { get; set; }
        public string extField2 { get; set; }
        public string Browser { get; set; }
        public string OS { get; set; }
    }
}
