//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserObject()
        {
            this.Users = new HashSet<User>();
            this.UserStores = new HashSet<UserStore>();
        }
    
        public string OrgNo { get; set; }
        public string UserLogName { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string PasswordHint { get; set; }
        public string PhoneNo { get; set; }
        public string ExtNo { get; set; }
        public string MobileNo { get; set; }
        public string FaxNo { get; set; }
        public string EmailAddress { get; set; }
        public string Department { get; set; }
        public string UserLevel { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveStatus { get; set; }
    
        public virtual BCU BCU { get; set; }
        public virtual BPSN BPSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserStore> UserStores { get; set; }
    }
}
