//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput.Modle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PickupDBEntities1 : DbContext
    {
        public PickupDBEntities1()
            : base("name=PickupDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PickupA> PickupAs { get; set; }
        public virtual DbSet<PickupB> PickupBs { get; set; }
        public virtual DbSet<ReadyOrderA> ReadyOrderAs { get; set; }
        public virtual DbSet<ReadyOrderB> ReadyOrderBs { get; set; }
        public virtual DbSet<NoticeA> NoticeAs { get; set; }
        public virtual DbSet<NoticeB> NoticeBs { get; set; }
    }
}
