//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickupA()
        {
            this.PickupBs = new HashSet<PickupB>();
            this.ReadyOrderAs = new HashSet<ReadyOrderA>();
        }
    
        public string OrderID { get; set; }
        public string OrderStore { get; set; }
        public string OrderName { get; set; }
        public Nullable<long> OrderAmount { get; set; }
        public string OrderSate { get; set; }
        public string OrderUploade { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderStaff { get; set; }
        public Nullable<long> OrderDifference { get; set; }
        public string OrderSpendTime { get; set; }
        public string OrderTrunState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupB> PickupBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyOrderA> ReadyOrderAs { get; set; }
    }
}
