//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupB
    {
        public long OrderSN { get; set; }
        public string OrderID { get; set; }
        public string Order_Location { get; set; }
        public string Order_Type { get; set; }
        public string Order_Color { get; set; }
        public string Order_Size { get; set; }
        public Nullable<long> Order_Amount { get; set; }
        public Nullable<long> Order_PickAmount { get; set; }
        public string Order_Barcode { get; set; }
        public Nullable<long> Order_BoxNum { get; set; }
        public string Order_BoxState { get; set; }
        public string Order_Store { get; set; }
        public string Order_State { get; set; }
        public string Order_Location2 { get; set; }
        public Nullable<long> Order_Stock { get; set; }
    
        public virtual PickupA PickupA { get; set; }
    }
}
