//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadyOrderB
    {
        public long RB_ID { get; set; }
        public Nullable<long> RB_Maping_RA_ID { get; set; }
        public string RB_OrderSN { get; set; }
        public string RB_Barcode { get; set; }
        public string RB_Type { get; set; }
        public string RB_Color { get; set; }
        public string RB_Size { get; set; }
        public Nullable<long> RB_Amount { get; set; }
    
        public virtual ReadyOrderA ReadyOrderA { get; set; }
    }
}
