//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesInput.Modle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadyOrderA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReadyOrderA()
        {
            this.ReadyOrderBs = new HashSet<ReadyOrderB>();
        }
    
        public long RA_ID { get; set; }
        public string RA_Maping_PU_ID { get; set; }
        public Nullable<long> RA_BoxID { get; set; }
        public string RA_Maping_ERP_ID { get; set; }
        public Nullable<System.DateTime> RA_Date { get; set; }
        public string RA_State { get; set; }
        public string RA_Store { get; set; }
        public string RA_Name { get; set; }
        public string RA_Staff { get; set; }
        public Nullable<long> RA_Amount { get; set; }
        public string RA_Img { get; set; }
    
        public virtual PickupA PickupA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadyOrderB> ReadyOrderBs { get; set; }
    }
}
